<!DOCTYPE html>
<html lang="ja">

	<?php require_once '../html/header.phtml';?>

	<title>各種設定一覧</title>
	</head>
	<body>
		<div class="container">
			<?php require_once '../html/menuArea.phtml';?>

			<div class="box main-container cleafix">
				<div class="clearfix" style="padding:0 100px;">
					<table border="2" class="float-left">
						<tr>
							<th colspan = "6">
							カラー 一覧
							</th>
						</tr>
						<tr class="record">
							<th>表示色</th>
							<th>色名</th>
							<th>変更/削除</th>
						</tr>
					<?php foreach($model->getColorList() as $num => $col):?>
						<tr>
							<form action="./managementElements.php" method="POST">
								<td>
									<input type="color" name="c_code" value="<?=$col["code"];?>">
								</td>

								<td>
									<input type="text"
										   name="c_name"
										   class="elements"
										   id="c_name<?php echo $num;?>"
										   value="<?=$col["c-name"];?>">
								</td>

								<td>
									<input type="submit" value="変更" class="c_update"
										   data-execute="c_update" data-index="<?php echo $num;?>">
									<input type="submit" value="削除" class="c_delete"
										   data-execute="c_delete" data-index="<?php echo $num;?>">
									<input type="hidden" name="execute" class="execute" value="">
									<input type="hidden" name="colorid" value="<?=$col["colorid"];?>">
								</td>
							</form>
						</tr>
					<?php endforeach;?>
						<tr>
							<th colspan="3">新規登録</th>
						</tr>
						<tr>
							<form action="./managementElements.php" method="POST">
								<td>
									<input type="color" name="c_code">
								</td>

								<td>
									<input type="text"
										   name="c_name"
										   id="insertColor"
										   size="7"
										   maxlength="10"
										   class="elements">
								</td>

								<td>
									<center>
										<input type="submit" value="登録" class="insert" id="c_insert">
										<input type="hidden" name="execute" value="c_insert">
									</center>
								</td>
							</form>
						</tr>
					</table>

					<table border="2" class="positiontable">
						<tr>
							<th colspan = "6">
							役割 一覧
							</th>
						</tr>
						<tr class="record">
							<th>役割名</th>
							<th>色</th>
							<th>変更</th>
						</tr>
					<?php foreach($model->getPositionList() as $index => $pos):?>
						<form action="./managementElements.php" method="POST">
							<tr>
							<?php if($pos["p-name"] == "講師" || $pos["p-name"] == "セミナー"){?>
								<td>
									<?=$pos["p-name"];?>
									<input type="hidden" name="p_name" value="<?=$pos["p-name"];?>">
								</td>
							<?php }else{?>
								<td>
									<input type="text"
										   class="elements"
										   id="p_name<?php echo $index;?>"
										   name="p_name"
										   value="<?=$pos["p-name"];?>">
								</td>
							<?php }?>
								<td>
									<input type="color" name="p_code" value="<?=$pos["color"];?>">
								</td>

								<td>
									<input type="submit" value="変更" class="p_update"
										   data-execute="p_update" data-index="<?php echo $index;?>">
									<?php if(!($pos["positionid"] == 1 || $pos["positionid"] == 2)):?>
										<input type="submit" value="削除"
											   class="p_delete" data-execute="p_delete" data-index="<?php echo $index;?>">
									<?php endif;?>
									<input type="hidden" name="execute" class="execute" value="">
									<input type="hidden" name="positionid" value="<?=$pos["positionid"];?>">
								</td>
							</tr>
						</form>
						<?php endforeach;?>
						<tr>
							<th colspan="3">新規登録</th>
						</tr>
						<tr>
							<form action="./managementElements.php" method="POST">
								<td>
									<input type="text" name="p_name" id="insertPosition" class="elements">
								</td>

								<td>
									<input type="color" name="p_code">
								</td>

								<td align="center">
									<input type="submit" value="登録" class="insert" id="p_insert">
									<input type="hidden" name="execute" value="p_insert">
								</td>
							</form>
						</tr>
					</table>

					<!--
					<table border="2" class="float-right">
						<tr>
							<th colspan = "6">
							ステータス 一覧
							</th>
						</tr>
						<tr class="record">
							<th>ステータス名</th>
							<th>変更/削除</th>
						</tr>
						<?php /*foreach($model->getStatusList() as $sta):?>
						<tr>
							<form action="./managementElements.php" method="POST">
							<?php if($sta["statusid"] <= 6){?>
								<td>
									<?=$sta["name"]?>
								</td>
							<?php }else{?>
								<td>
									<input type="text" name="s_name" class="elements" value="<?=$sta["name"]?>">
								</td>

								<td>
									<input type="submit" value="変更" class="update" data-execute="s_update">
									<input type="submit" value="削除" class="delete" data-execute="s_delete">
									<input type="hidden" name="execute" class="execute" value="">
									<input type="hidden" name="statusid" value="<?=$sta["statusid"];?>">
								</td>
							<?php }?>
							</form>
						</tr>
						<?php endforeach;*/?>
						<tr>
							<th colspan="2">新規登録</th>
						</tr>
						<tr>
							<form action="./managementElements.php" method="POST">
								<td>
									<input type="text" name="s_name" class="elements">
								</td>

								<td>
									<center>
										<input type="submit" value="登録" class="insert">
										<input type="hidden" name="execute" value="s_insert">
									</center>
								</td>
							</form>
						</tr>
					</table>
					-->

				</div>

			<?php require_once '../html/footer.phtml';?>

		</div>
	</body>
</html>