<!DOCTYPE html>
<html lang="ja">
	<?php require_once '../html/header.phtml';?>

	<title>セミナー登録画面</title>

	</head>
	<body>
		<div class="container"><!-- container -->

			<?php require_once '../html/menuArea.phtml';?>

			<?php if($model->getExecute() == "insert"){?>

				<div class="box main-container"><!-- main-container -->

					<div class="insertUser"><!-- セミナー登録情報確認ブロック -->
						<p>以下の情報でセミナーを登録しました</p>

						<table align="center" id="padding">
							<tr>
								<td>セミナー名</td>
								<td><?php echo $model->getEventName();?></td>
							</tr>
							<tr>
								<td>セミナー略名</td>
								<td><?php echo $model->getShortName();?></td>
							</tr>
							<tr>
								<td>表示色</td>
								<td>
									<span class="eventSquare" style="background-color: <?php echo $model->getColor();?>">
									</span>
								</td>
							</tr>
						</table>

						<p>
							<a href="./insertEvent.php">セミナー登録画面に戻る</a>
							 /
							<a href="../eventList/eventList.php">セミナー一覧に戻る</a>
						</p>
					</div><!-- /セミナー登録情報確認ブロック -->

				</div><!-- main-container -->

			<?php }else{?>

				<div class="box main-container"><!-- main-container -->

					<div class="insertUser"><!-- セミナー登録フォームブロック -->

						<p>セミナー登録</p>

						<form action="" method="POST">

							<table align="center" id="padding">

								<tr>
									<td>セミナー名</td>
									<td><input type="text" name="eventName" maxlength="20"></td>
								</tr>
								<tr>
									<td>セミナー略名</td>
									<td><input type="text" name="shortName" maxlength="2"></td>
								</tr>
								<tr>
									<td>表示色</td>
									<td><input type='color' name='color' value='#fe0032' /></td>
								</tr>

							</table>
							<p>
								<input type="submit" id="insert" value="登録">
								<input type="hidden" name="execute" value="insert">
							</p>

						</form>

					</div><!-- /セミナー登録フォームブロック -->

				</div><!-- /main-container -->
			<?php }?>

			<?php require_once '../html/footer.phtml';?>

		</div><!-- /container -->
	</body>
</html>
