<?php

?>
<DOCTYPE html>
<html lang="ja">
	<?php require_once '../html/header.phtml';?>
		<title>ログイン画面</title>
	</head>
	<body>
		<div class="container">
			<div class="box title">
			<header class="box">
				<h1 class="title">勤怠管理システム</h1>
			</header>
			</div>
			<div class="box main-container">

				<div align="center">
					<h4>
						<font color="red"><?php echo $model->getError();?></font>
					</h4>
				</div>

				<div class="loginbox"><!-- ログインフォーム用ボックス -->
					<div class="loginTitle"><!-- ボックスタイトル -->
						ログイン
					</div>
					<div class="loginForm">
						<form action="login.php" name="loginForm" method="post">
							<br>

							ユーザーID<br>
							<input type="text" name="userid" value="<?php echo $model->getUserid();?>"><br><br>
							パスワード<br>
							<input type="password" name="password"  value="<?php echo $model->getPassword();?>"><br><br>

							<input type="submit" name="execute" value="ログイン">

						</form>
					</div>

				</div>

			</div>

			<?php require_once '../html/footer.phtml';?>
		</div>
	</body>
</html>