<!DOCTYPE html>
<html lang="ja">
	<head>
		<meta charset="UTF-8">
		<link rel="stylesheet" href="../css/design.css">
		<link rel="stylesheet" href="../css/content.css">
		<link rel="stylesheet" href="../jquery/jquery-ui.css">
		<title>ユーザー設定変更画面</title>
		<script type="text/javascript" src="../jquery/jquery-1.11.3.min.js"></script>
		<script src="../jquery/jquery-ui.js"></script>
		<script src="../script/updateUser.js"></script>
		<script type="text/javascript" src="../script/logout.js"></script>
	</head>
	<body>
		<div class="container">
			<header class="box">
				<h1 class="title">勤怠管理システム</h1>
			</header>

			<div class="box width70 clearfix">
				<div class="userInfo float-left">
					<p>
						ユーザー名 : <?php echo $_SESSION['userinfo']['name'];?> /
						権限 : <?php if($_SESSION['userinfo']['authority'] == 2){?>
								管理者
							  <?php }else{?>
							  	一般ユーザー
							  <?php }?>
					</p>
				</div>
				<div class="userInfo float-right">
					<p><a href="../login/login.php?execute=logout" id="logoutLink">ログアウト</a></p>
				</div>
			</div>

			<div class="box menu"><!-- ヘッダーメニュー-->
				<ul id="dropmenu">
	 				<li><a href="../mainMenu/mainMenu.php">メニュー</a>
	   			 		<ul>
	    				</ul>
	 				 </li>
	  				<li><a href="../overallWorkTime/overallWorkTime.php">勤務時間表</a>
	   					<ul>
	   					</ul>
	 				</li>
	 				<li><a href="../settingHoliday/settingHoliday.php">休日設定</a>
	    				<ul>
	   					</ul>
	 				</li>
	  				<li><a href="#">管理設定</a>
	   					<ul>
	     					<li><a href="./updateUser.php">ユーザー設定変更</a></li>
	     					<li><a href="../insertUser/insertUser.php">ユーザー登録</a></li>
	     					<li><a href="../eventList/eventList.php">セミナー一覧</a></li>
	     					<li><a href="../insertEvent/insertEvent.php">セミナー登録</a></li>
	   						<li><a href="../managementElements/managementElements.php">各種設定一覧</a></li>
	   					</ul>
	  				</li>
	  				<li><a href="../settingRestTime/settingRestTime.php">休憩時間設定</a>
	   					<ul>
	   					</ul>
	  				</li>
				</ul>
			</div>

			<div class="box main-container">

					<table align="center" border="2">
						<tr>
							<th colspan = "8">
							ユーザー 一覧
							</th>
						</tr>
						<tr class="record">
							<th>ユーザー名</th>
							<th>ユーザーID</th>
							<th>パスワード</th>
							<th>権限</th>
							<th>勤務形態</th>
							<th>active/<br>inactive</th>
							<th>表示色</th>
							<th>変更/削除</th>
						</tr>
					<?php foreach($model->getAccountList() as $num => $value):?>
						<tr>
							<form action="" method="POST">
								<td>
									<font color="<?php echo $value["code"];?>" id="name<?php echo $num;?>">
										<?php echo $value["name"];?>
									</font>
								</td>

								<td id="userid<?php echo $num;?>">
									<?php echo $value["userid"];?>
								</td>

								<td id="password<?php echo $num;?>">
									<?php echo $value["password"];?>
								</td>

								<td id="authority<?php echo $num;?>">
									<?php if($value["authority"] == 2){?>
										管理者
									<?php }else{?>
										一般ユーザー
									<?php }?>
								</td>

								<td id="worktype<?php echo $num;?>">
									<?php if($value["worktype"] == 1){?>
										常勤
									<?php }else{?>
										非常勤
									<?php }?>
								</td>

								<td id="display<?php echo $num;?>">
									<?php if($value["display"] == 1){?>
										active
									<?php }else{?>
										inactive
									<?php }?>
								</td>

								<td id="colorid<?php echo $num;?>">
									<font color="<?php echo $value["code"];?>">
										<?php echo $value["c-name"];?>
									</font>
								</td>

								<td>
									<input type="button" value="変更" class="update"
												id="update<?php echo $num;?>"
												data-name="<?php echo $value["name"];?>"
												data-accountid="<?php echo $value["accountid"];?>"
												data-userid="<?php echo $value["userid"];?>"
												data-password="<?php echo $value["password"];?>"
												data-authority="<?php echo $value["authority"];?>"
												data-worktype="<?php echo $value["worktype"];?>"
												data-display="<?php echo $value["display"];?>"
												data-colorid="<?php echo $value["colorid"];?>"
												data-code="<?php echo $value["code"];?>"
												data-execute="update"
												data-index="<?php echo $num;?>">
									<input type="submit" value="削除" class="delete"
												data-execute="delete" data-index="<?php echo $num;?>">
									<input type="hidden" name="execute" class="execute">
									<input type="hidden" name="accountid" value="<?php echo $value["accountid"]?>">

								</td>
							</form>
						</tr>
					<?php endforeach;?>
					</table>




			<footer class="box footer">
				<p>Copyright © 2010-2015 FusionOne Co.,Ltd. All Rights Reserved.</p>
			</footer>

			<div id="jquery-ui-dialog" title="ユーザー情報変更">
			    <form>
			    <fieldset>
			    <p>ユーザー名：<span id="name"></span></p>
				<p>
		            <label for="jquery-ui-dialog-form-userid">ユーザーID：</label>
		            <input type="text" name="userid" id="userid" maxlength="20">
		        </p>

		        <p>
		            <label for="jquery-ui-dialog-form-password">パスワード：</label>
		           	<input type="text" name="password"  id="password" maxlength="20">
		        </p>

		        <p>
		            <label for="jquery-ui-dialog-form-authority">ユーザー権限：</label>
		           	<select name="authority" id="authority">
						<option value="2">管理者</option>
						<option value="1">一般ユーザー</option>
					</select>

		        </p>

		        <p>
		            <label for="jquery-ui-dialog-form-worktype">勤務形態：<br></label>
		           	<select name="worktype" id="worktype">
						<option value="1">常勤</option>
						<option value="2">非常勤</option>
					</select>

		        </p>

		        <p>
		            <label for="jquery-ui-dialog-form-authority">active/inactive：</label>
		            <br>
		            <select name="display" id="display">
						<option value="1">active</option>
						<option value="2">inactive</option>
					</select>

		        </p>

		        <p>
		            <label for="jquery-ui-dialog-form-colorid">表示色：</label>
		            <br>
		            <select name="colorid" id="colorid">
						<?php foreach($model->getColorList() as $col):?>

							<option value="<?php echo $col["colorid"];?>"
							style="color:<?php echo $col["code"];?>;"
							data-code="<?php echo $col["code"];?>">

								<?php echo $col["c-name"];?>

							</option>
						<?php endforeach;?>
					</select>

		        </p>

			    </fieldset>

			    </form>
			</div>

			<div id="jquery-ui-dialog2" title="ユーザー情報変更">
			    <form>
			    <fieldset>
			        <p>
			        	以下のセミナー情報を変更しました
			        </p>

			        <table id="changeEventTable">
			        	<tr>
			        		<th class="eventTableTitle" colspan="3">
			        			<span id="nameDisp"></span>変更情報
			        		</th>

			        	</tr>

			        	<tr>
			        		<th></th>
			        		<th>変更前</th>
			        		<th>変更後</th>
			        	</tr>

			        	<tr>
			        		<th>
			        			ユーザーID
			        		</th>
			        		<td>
			        			<span id="oldUseridDisp"></span>
			        		</td>
			        		<td>
			        			<span id="useridDisp"></span>
			        		</td>
			        	</tr>

			        	<tr>
			        		<th>
			        			パスワード
			        		</th>
			        		<td>
			        			<span id="oldPasswordDisp"></span>
			        		</td>
			        		<td>
			        			<span id="passwordDisp"></span>
			        		</td>
			        	</tr>

			        	<tr>
			        		<th>
			        			権限
			        		</th>
			        		<td>
			        			<span id="oldAuthorityDisp"></span>
			        		</td>
			        		<td>
			        			<span id="authorityDisp"></span>
			        		</td>
			        	</tr>

			        	<tr>
			        		<th>
			        			勤務形態
			        		</th>
			        		<td>
			        			<span id="oldWorktypeDisp"></span>
			        		</td>
			        		<td>
			        			<span id="worktypeDisp"></span>
			        		</td>
			        	</tr>

			        	<tr>
			        		<th>
			        			acitive/<br>
			        			inactive
			        		</th>
			        		<td>
			        			<span id="oldDisplayDisp"></span>
			        		</td>
			        		<td>
			        			<span id="displayDisp"></span>
			        		</td>
			        	</tr>

			        	<tr>
			        		<th>
			        			表示色
			        		</th>
			        		<td>
			        			<span id="oldColorDisp"></span>
			        		</td>
			        		<td>
			        			<span id="colorDisp"></span>
			        		</td>
			        	</tr>

			        </table>



			    </fieldset>

			    </form>
			</div>

		</div>
	</body>
</html>