<!DOCTYPE html>
<html lang="ja">
	<?php require_once '../html/header.phtml';?>

		<title>勤務時間表(全体)画面</title>
	</head>
	<body>
		<div class="container">
			<header class="box">
				<h1 class="title">勤怠管理システム</h1>
			</header>

			<div class="box width70 clearfix">
				<div class="userInfo float-left">
					<p>
						ユーザー名 : <?php echo $_SESSION['userinfo']['name'];?> /
						権限 : <?php if($_SESSION['userinfo']['authority'] == 2){?>
								管理者
							  <?php }else{?>
							  	一般ユーザー
							  <?php }?>
					</p>
				</div>
				<div class="userInfo float-right">
					<p><a href="../login/login.php">ログアウト</a></p>
				</div>
			</div>

			<div class="box menu"><!-- ヘッダーメニュー-->
				<ul id="dropmenu">
	 				<li><a href="../mainMenu/mainMenu.php">メニュー</a>
	   			 		<ul>
	    				</ul>
	 				</li>
	  				<li><a href="overallWorkTime.php">勤務時間表</a>
	   					<ul>
	   					</ul>
	 				</li>
	 				<li><a href="../settingHoliday/settingHoliday.php">休日設定</a>
	    				<ul>
	   					</ul>
	 				</li>
	  				<li><a href="#">管理設定</a>
	   					<ul>
	     					<li><a href="../updateUser/updateUser.php">ユーザー設定変更</a></li>
	     					<li><a href="../insertUser/insertUser.php">ユーザー登録</a></li>
	     					<li><a href="../eventList/eventList.php">セミナー一覧</a></li>
	     					<li><a href="../insertEvent/insertEvent.php">セミナー登録</a></li>
	     					<li><a href="../managementElements/managementElements.php">各種設定一覧</a></li>
	   					</ul>
	  				</li>
	  				<li><a href="../settingRestTime/settingRestTime.php">休憩時間設定</a>
	   					<ul>
	   					</ul>
	  				</li>
				</ul>
			</div>

			<div class="box main-container">
		<div class="workTime">
					<p>条件検索</p>
					<div class="selectbox">
					<form action="overallWorkTime.php" method="POST">
						<table>
							<tr>
							<!--表示非表示の切り替え　月次-->

								<?php $yearList = createYearSet();?>

								<td id="formYear">
									<select name="year">
										<option value="<?php echo date("Y");?>">
											<?php echo date("Y");?>
										</option>
										<?php for($i=0;$i<count($yearList);$i++){?>
											<option value="<?php echo $yearList[$i];?>">
												<?php echo $yearList[$i];?>
											</option>
										<?php }?>
									</select> 年
								</td>

							<!--表示非表示の切り替え　月次-->
						       	<td id="formMonth">
									<input type="month" name="month" placeholder="例)2014-01" value="<?=$model->getMonth();?>">
								</td>

							<!--表示非表示の切り替え　期間-->
								<td id="formPeriod">
									 開始期間
									<input type="month" name="startDay" placeholder="例)2014-08" size="15" value="<?=$model->getStartDay();?>">
									～ 終了期間
									<input type="month" name="endDay" placeholder="例)2014-09" size="15" value="<?=$model->getEndDay();?>">
								</td>
							</tr>
						</table>
表示時間:
            <label><input type="radio" name="work" value="year" onclick="formChange();"
            			<?php if($model->getWork() == 'year'){echo 'checked';}?>>年次</label>
            <label><input type="radio" name="work" value="month" onclick="formChange();"
						<?php if($model->getWork() == 'month' || $model->getWork() == 'months'){echo ' checked';}?>>月次</label>
            <label><input type="radio" name="work" value="period" onclick="formChange();"
            			<?php if($model->getWork() == 'period'){echo ' checked';}?>>期間</label>



						<p>氏名
						<?php $selectid = $model->getAccountId();?>
							<select name="accountid">
								<option value="%%" <?php if($selectid == ""){echo ' selected';}?>>全体</option>

								<?php foreach ($model->getAccountData() as $account){?>
									<option value="<?php echo $account["accountid"];?>"
													<?php if($selectid == $account["accountid"]){echo ' selected';}?>>
										<?php echo $account["name"];?>
									</option>
								<?php }?>

							</select>

							<span style="margin-left:50%;">
								<input type="submit" value="表示" id="display">
								<input type="hidden" name="execute" value="disp">
								<input type="hidden" name="extend" value="">
							</span>
						</p>
						</form>
					</div>

					<br>
					<p>表示期間 : <?=$model->getInfomation();?></p>

					<div class="worksheet">
						<table>
							<tr class="record">
								<td>氏名</td>
								<td>出勤日<br>合計</td>
								<td>週平均<br>出勤日数</td>
								<td>欠席日数</td>
								<td>営業日数</td>
								<td>休憩時間</td>
								<td>労働時間<br>合計</td>
								<td>月平均<br>労働時間</td>
								<td>週平均<br>労働時間</td>
							</tr>
							<?php
							 if(is_array($model->getDisplayData())):
									foreach($model->getDisplayData() as $key => $value){

							?>
							<tr>
								<td><a href="../personalWorkTime/personalWorkTime.php?
										accountid=<?=$value['accountid'];?>
										&work=<?=$model->getWork();?>
										&extend=<?=$model->getExtend();?>"><?=$value['name'];?></a></td>
								<td><?php echo $value['workday'];?></td>
								<td><?php echo $value['aveWorkday']?></td>
								<td><?php echo $value['absence'];?></td>
								<td><?php echo $value['business'];?></td>
								<td><?php echo round($value['resttime'],2);?></td>
								<td><?php echo round($value['worktime'],2);?></td>
								<td><?php echo round($value['aveWorktimeMonth'],2);?></td>
								<td><?php echo $value['aveWorktimeWeek'];?></td>
							</tr>
							<?php
								}
							endif;
							?>
								<tr>
									<th>合計</th>
									<th><?php echo $model->getSelSumArray('workday');?></th>
									<th><?php echo $model->getSelSumArray('aveWorkday');?></th>
									<th><?php echo $model->getSelSumArray('absence');?></th>
									<th><?php echo $model->getSelSumArray('business');?></th>
									<th><?php echo round($model->getSelSumArray('resttime'),2);?></th>
									<th><?php echo round($model->getSelSumArray('worktime'),2);?></th>
									<th><?php echo round($model->getSelSumArray('aveWorktimeMonth'),2);?></th>
									<th><?php echo $model->getSelSumArray('aveWorktimeWeek');?></th>
								</tr>
							<tr>
								<th>平均</th>
								<th><?php echo $model->getSelAveArray('workday');?></th>
								<th><?php echo $model->getSelAveArray('aveWorkday');?></th>
								<th><?php echo $model->getSelAveArray('absence');?></th>
								<th><?php echo $model->getSelAveArray('business');?></th>
								<th><?php echo $model->getSelAveArray('resttime');?></th>
								<th><?php echo $model->getSelAveArray('worktime');?></th>
								<th><?php echo $model->getSelAveArray('aveWorktimeMonth');?></th>
								<th><?php echo $model->getSelAveArray('aveWorktimeWeek');?></th>
							</tr>
						</table>

						<?php
							if(is_array($model->getMonthDispData())):
						 ?>
						 <div class="worksheet">
						 	<br>
							<p><?php echo $model->getYear();?>年度月別個人データ</p>
							<br>

							 <table>
								<tr class="record">
									<td>月</td>
									<td>出勤日<br>合計</td>
									<td>週平均<br>出勤日数</td>
									<td>欠席日数</td>
									<td>営業日数</td>
									<td>休憩時間</td>
									<td>労働時間<br>合計</td>
									<td>月平均<br>労働時間</td>
									<td>週平均<br>労働時間</td>
								</tr>
							 <?php
									foreach($model->getMonthDispData()as $key => $value){
							 ?>
								<tr>
									<td><?php echo $value['name'];?></td>
									<td><?php echo $value['workday'];?></td>
									<td><?php echo $value['aveWorkday']?></td>
									<td><?php echo $value['absence'];?></td>
									<td><?php echo $value['business'];?></td>
									<td><?php echo $value['resttime'];?></td>
									<td><?php echo $value['worktime'];?></td>
									<td><?php echo $value['aveWorktimeMonth'];?></td>
									<td><?php echo $value['aveWorktimeWeek'];?></td>
								</tr>

							<?php
							}
							?>
								<tr>
									<th>合計</th>
									<th><?php echo $model->getSelMonthSumArray('workday');?></th>
									<th><?php echo $model->getSelSumArray('aveWorkday');?></th>
									<th><?php echo $model->getSelMonthSumArray('absence');?></th>
									<th><?php echo $model->getSelMonthSumArray('business');?></th>
									<th><?php echo $model->getSelMonthSumArray('resttime');?></th>
									<th><?php echo $model->getSelMonthSumArray('worktime');?></th>
									<th><?php echo $model->getSelMonthSumArray('aveWorktimeMonth');?></th>
									<th><?php echo $model->getSelMonthSumArray('aveWorktimeWeek');?></th>
								</tr>
								<tr>
									<th>平均</th>
									<th><?php echo $model->getSelMonthAveArray('workday');?></th>
									<th><?php echo $model->getSelAveArray('aveWorkday');?></th>
									<th><?php echo $model->getSelMonthAveArray('absence');?></th>
									<th><?php echo $model->getSelMonthAveArray('business');?></th>
									<th><?php echo $model->getSelMonthAveArray('resttime');?></th>
									<th><?php echo $model->getSelMonthAveArray('worktime');?></th>
									<th><?php echo $model->getSelMonthAveArray('aveWorktimeMonth');?></th>
									<th><?php echo $model->getSelMonthAveArray('aveWorktimeWeek');?></th>
								</tr>
							</table>
						</div>
						<?php
						endif;
						?>
						<p class="right"><button class="exportExcel">excelに出力</button>　　<button class="exportPDF">PDFに出力</button></p>
					</div>
				</div>
			</div>

			<footer class="box footer">
				<p>Copyright © 2010-<?=date("Y")?> FusionOne Co.,Ltd. All Rights Reserved.</p>
			</footer>

		</div>

	</body>
</html>