<!DOCTYPE html>
<html lang="ja">
	<head>
		<meta charset="UTF-8">
		<link rel="stylesheet" href="../css/design.css">
		<link rel="stylesheet" href="../css/content.css">
		<script src="../jquery/jquery-1.11.3.min.js"></script>
		<script src="../script/workTime.js"></script>
		<script>
		function formChange(){
			radio = document.getElementsByName('work')
			if(radio[0].checked) {

				//フォーム
				document.getElementById('formYear').style.display = "";
				document.getElementById('formMonth').style.display = "none";
				document.getElementById('formWeek').style.display = "none";
				document.getElementById('formDay').style.display = "none";
				document.getElementById('formPeriod').style.display = "none";

			}else if(radio[1].checked) {

				//フォーム
				document.getElementById('formYear').style.display = "none";
				document.getElementById('formMonth').style.display = "";
				document.getElementById('formWeek').style.display = "none";
				document.getElementById('formDay').style.display = "none";
				document.getElementById('formPeriod').style.display = "none";

			}else if(radio[2].checked) {

				//フォーム
				document.getElementById('formYear').style.display = "none";
				document.getElementById('formMonth').style.display = "none";
				document.getElementById('formWeek').style.display = "";
				document.getElementById('formDay').style.display = "none";
				document.getElementById('formPeriod').style.display = "none";

			}else if(radio[3].checked) {

				//フォーム
				document.getElementById('formYear').style.display = "none";
				document.getElementById('formMonth').style.display = "none";
				document.getElementById('formWeek').style.display = "none";
				document.getElementById('formDay').style.display = "";
				document.getElementById('formPeriod').style.display = "none";

			}else if(radio[4].checked) {

				//フォーム
				document.getElementById('formYear').style.display = "none";
				document.getElementById('formMonth').style.display = "none";
				document.getElementById('formWeek').style.display = "none";
				document.getElementById('formDay').style.display = "none";
				document.getElementById('formPeriod').style.display = "";

			}
		}

		//オンロードさせ、リロード時に選択を保持
		window.onload = formChange;
		</script>

		<title>勤務時間表(全体)画面</title>
	</head>
	<body>
		<div class="container">
			<header class="box">
				<h1 class="title">勤怠管理システム</h1>
			</header>

			<div class="box width70 clearfix">
				<div class="userInfo float-left">
					<p>ユーザー名 : admin / 権限 : 管理者</p>
				</div>
				<div class="userInfo float-right">
					<p><a href="../login/login.php">ログアウト</a></p>
				</div>
			</div>

			<div class="box menu"><!-- ヘッダーメニュー-->
				<ul id="dropmenu">
	 				<li><a href="../mainMenu/mainMenu.php">メニュー</a>
	   			 		<ul>
	    				</ul>
	 				</li>
	  				<li><a href="overallWorkTime.php">勤務時間表</a>
	   					<ul>
	   					</ul>
	 				</li>
	 				<li><a href="../settingHoliday/settingHoliday.php">休日設定</a>
	    				<ul>
	   					</ul>
	 				</li>
	  				<li><a href="#">ユーザー設定</a>
	   					<ul>
	     					<li><a href="../updateUser/updateUser.php">ユーザー設定変更</a></li>
	     					<li><a href="../insertUser/insertUser.php">ユーザー登録</a></li>
	   					</ul>
	  				</li>
	  				<li><a href="../settingRestTime/settingRestTime.php">休憩時間設定</a>
	   					<ul>
	   					</ul>
	  				</li>
				</ul>
			</div>

			<div class="box main-container">
		<div class="workTime">
					<p>条件検索</p>
					<div class="selectbox">
					<form action="overallWorkTime.php" method="POST">
						<table>
							<tr>
							<!--表示非表示の切り替え　月次-->

								<td id="formYear">
									<select name="year">
										<option value="2015">2015</option>
										<option value="2014">2014</option>
										<option value="2013">2013</option>
									</select> 年
								</td>

							<!--表示非表示の切り替え　月次-->
						       	<td id="formMonth">
									<input type="month" name="month">
								</td>

							<!--表示非表示の切り替え　週次-->
								<td id="formWeek">
									<input type="motnth" name="week[]">
									<select name="week[]">
										<option value="first">1</option>
										<option value="second">2</option>
										<option value="third">3</option>
										<option value="foruth">4</option>
										<option value="fifth">5</option>
									</select>
								</td>
								</td>

							<!--表示非表示の切り替え　日時-->
								<td id="formDay">
									 <input type="date" name="day">
								</td>

							<!--表示非表示の切り替え　期間-->
								<td id="formPeriod">
									 開始期間
									<input type="date" name="startDay">　
									終了期間
									<input type="date" name="endDay">
								</td>
							</tr>
						</table>
表示時間:
            <label><input type="radio" name="work" value="year" onclick="formChange();">年次</label>
            <label><input type="radio" name="work" value="month" onclick="formChange();" checked="checked">月次</label>
            <label><input type="radio" name="work" value="week" onclick="formChange();">週次</label>
            <label><input type="radio" name="work" value="day" onclick="formChange();">日時</label>
            <label><input type="radio" name="work" value="period" onclick="formChange();">期間</label>
						&nbsp;&nbsp;&nbsp;<input type="submit" value="表示">

						<p>氏名
							<select name="name">
								<option value="1">全体</option>
								<option value="2">Bさん</option>
								<option value="3">Cさん</option>
								<option value="4">Dさん</option>
							</select>

							<span style="margin-left:50%;">
								<input type="submit" value="検索">
								<input type="submit" value="全件表示">
							</span>
						</p>
						</form>
					</div>

					<br>
					<p>表示期間 : <?=$model->getInfomation();?></p>
					<br>

					<div class="worksheet">
						<table>
							<tr class="record">
								<td>氏名</td>
								<td>出勤日合計</td>
								<td>欠席日数</td>
								<td>営業日数</td>
								<td>休憩時間</td>
								<td>労働時間合計</td>
								<td>月平均<br>労働時間</td>
								<td>週平均<br>労働時間</td>
							</tr>
							<?php foreach($model->getDisplayData() as $key => $value){?>
							<tr>
								<td><a href="personalWorkTime.php"><?php echo $value['name'];?></a></td>
								<td><?php echo $value['workday'];?></td>
								<td><?php echo $value['absence'];?></td>
								<td><?php echo $value['business'];?></td>
								<td><?php echo $value['resttime'];?></td>
								<td><?php echo $value['worktime'];?></td>
								<td><?php echo $value['aveWorktimeMonth'];?></td>
								<td><?php echo $value['aveWorktimeWeek'];?></td>
							</tr>
							<?php }?>
								<tr>
									<th>合計</th>
									<th>64</th>
									<th>1</th>
									<th>66</th>
									<th>66.0</th>
									<th>380.0</th>
									<th>17.2</th>
									<th>17.2</th>
								</tr>
							<tr>
								<th>平均</th>
								<th>21.3</th>
								<th>0.3</th>
								<th>22.0</th>
								<th>22.0</th>
								<th>126.6</th>
								<th>5.7</th>
								<th>5.7</th>
							</tr>
						</table>
						<p class="right"><button class="exportExcel">excelに出力</button>　　<button class="exportPDF">PDFに出力</button></p>
					</div>
				</div>
			</div>

			<footer class="box footer">
				<p>Copyright © 2010-2015 FusionOne Co.,Ltd. All Rights Reserved.</p>
			</footer>

		</div>

	</body>
</html>