<!DOCTYPE html>
<html lang="ja">
	<head>
		<meta charset="UTF-8">
		<link rel="stylesheet" href="../css/design.css">
		<link rel="stylesheet" href="../css/content.css">
		<script src="../jquery/jquery-1.11.3.min.js"></script>
		<script src="../script/workTime.js"></script>
		<script src="../script/overallWorkTime.js"></script>

		<title>勤務時間表(全体)画面</title>
	</head>
	<body>
		<div class="container">
			<header class="box">
				<h1 class="title">勤怠管理システム</h1>
			</header>

			<div class="box width70 clearfix">
				<div class="userInfo float-left">
					<p>
						ユーザー名 : <?php echo $_SESSION['userinfo']['name'];?> /
						権限 : <?php if($_SESSION['userinfo']['authority'] == 2){?>
								管理者
							  <?php }else{?>
							  	一般ユーザー
							  <?php }?>
					</p>
				</div>
				<div class="userInfo float-right">
					<p><a href="../login/login.php">ログアウト</a></p>
				</div>
			</div>

			<div class="box menu"><!-- ヘッダーメニュー-->
				<ul id="dropmenu">
	 				<li><a href="../mainMenu/mainMenu.php">メニュー</a>
	   			 		<ul>
	    				</ul>
	 				</li>
	  				<li><a href="overallWorkTime.php">勤務時間表</a>
	   					<ul>
	   					</ul>
	 				</li>
	 				<li><a href="../settingHoliday/settingHoliday.php">休日設定</a>
	    				<ul>
	   					</ul>
	 				</li>
	  				<li><a href="#">ユーザー設定</a>
	   					<ul>
	     					<li><a href="../updateUser/updateUser.php">ユーザー設定変更</a></li>
	     					<li><a href="../insertUser/insertUser.php">ユーザー登録</a></li>
	   					</ul>
	  				</li>
	  				<li><a href="../settingRestTime/settingRestTime.php">休憩時間設定</a>
	   					<ul>
	   					</ul>
	  				</li>
				</ul>
			</div>

			<div class="box main-container">
		<div class="workTime">
					<p>条件検索</p>
					<div class="selectbox">
					<form action="overallWorkTime.php" method="POST">
						<table>
							<tr>
							<!--表示非表示の切り替え　月次-->

								<?php $yearList = createYearSet();?>

								<td id="formYear">
									<select name="year">
										<option value="<?php echo date("Y");?>">
											<?php echo date("Y");?>
										</option>
										<?php for($i=0;$i<count($yearList);$i++){?>
											<option value="<?php echo $yearList[$i];?>">
												<?php echo $yearList[$i];?>
											</option>
										<?php }?>
									</select> 年
								</td>

							<!--表示非表示の切り替え　月次-->
						       	<td id="formMonth">
									<input type="month" name="month" value="<?php echo date("Y-m");?>">
								</td>

							<!--表示非表示の切り替え　週次-->
								<td id="formWeek">
									<input type="motnth" name="week[]">
									<select name="week[]">
										<option value="first">1</option>
										<option value="second">2</option>
										<option value="third">3</option>
										<option value="foruth">4</option>
										<option value="fifth">5</option>
									</select>
								</td>
								</td>

							<!--表示非表示の切り替え　日時-->
								<td id="formDay">
									 <input type="date" name="day">
								</td>

							<!--表示非表示の切り替え　期間-->
								<td id="formPeriod">
									 開始期間
									<input type="date" name="startDay">　
									終了期間
									<input type="date" name="endDay">
								</td>
							</tr>
						</table>
表示時間:
            <label><input type="radio" name="work" value="year" onclick="formChange();">年次</label>
            <label><input type="radio" name="work" value="month" onclick="formChange();" checked="checked">月次</label>
            <label><input type="radio" name="work" value="week" onclick="formChange();">週次</label>
            <label><input type="radio" name="work" value="day" onclick="formChange();">日時</label>
            <label><input type="radio" name="work" value="period" onclick="formChange();">期間</label>


						<p>氏名
							<select name="accountid">
								<option value="" selected>全体</option>
								<?php foreach ($model->getAccountData() as $account){?>
									<option value="<?php echo $account["accountid"];?>">
										<?php echo $account["name"];?>
									</option>
								<?php }?>
							</select>

							<span style="margin-left:50%;">
								<input type="submit" value="表示" id="display">
								<input type="hidden" name="execute" value="disp">
							</span>
						</p>
						</form>
					</div>

					<br>
					<p>表示期間 : <?=$model->getInfomation();?></p>
					<br>

					<div class="worksheet">
						<table>
							<tr class="record">
								<td>氏名</td>
								<td>出勤日合計</td>
								<td>欠席日数</td>
								<td>営業日数</td>
								<td>休憩時間</td>
								<td>労働時間合計</td>
								<td>月平均<br>労働時間</td>
								<td>週平均<br>労働時間</td>
							</tr>
							<?php
							 if(is_array($model->getDisplayData())):
									foreach($model->getDisplayData() as $key => $value){

							?>
							<tr>
								<td><a href="../personalWorkTime/personalWorkTime.php?accountid=<?php echo $value['accountid'];?>"><?php echo $value['name'];?></a></td>
								<td><?php echo $value['workday'];?></td>
								<td><?php echo $value['absence'];?></td>
								<td><?php echo $value['business'];?></td>
								<td><?php echo $value['resttime'];?></td>
								<td><?php echo $value['worktime'];?></td>
								<td><?php echo $value['aveWorktimeMonth'];?></td>
								<td><?php echo $value['aveWorktimeWeek'];?></td>
							</tr>
							<?php
								}
							endif;
							?>
								<tr>
									<th>合計</th>
									<th><?php echo $model->getSelSumArray('workday');?></th>
									<th><?php echo $model->getSelSumArray('absence');?></th>
									<th><?php echo $model->getSelSumArray('business');?></th>
									<th><?php echo $model->getSelSumArray('resttime');?></th>
									<th><?php echo $model->getSelSumArray('worktime');?></th>
									<th><?php echo $model->getSelSumArray('aveWorktimeMonth');?></th>
									<th><?php echo $model->getSelSumArray('aveWorktimeWeek');?></th>
								</tr>
							<tr>
								<th>平均</th>
								<th><?php echo $model->getSelAveArray('workday');?></th>
								<th><?php echo $model->getSelAveArray('absence');?></th>
								<th><?php echo $model->getSelAveArray('business');?></th>
								<th><?php echo $model->getSelAveArray('resttime');?></th>
								<th><?php echo $model->getSelAveArray('worktime');?></th>
								<th><?php echo $model->getSelAveArray('aveWorktimeMonth');?></th>
								<th><?php echo $model->getSelAveArray('aveWorktimeWeek');?></th>
							</tr>
						</table>
						<p class="right"><button class="exportExcel">excelに出力</button>　　<button class="exportPDF">PDFに出力</button></p>
					</div>
				</div>
			</div>

			<footer class="box footer">
				<p>Copyright © 2010-2015 FusionOne Co.,Ltd. All Rights Reserved.</p>
			</footer>

		</div>

	</body>
</html>