<!DOCTYPE html>
<html lang="ja">
	<head>
		<meta charset="UTF-8">
		<link rel="stylesheet" href="../css/design.css">
		<link rel="stylesheet" href="../css/content.css">
		<link rel="stylesheet" href="../jquery/jquery-ui.css">
		<script src="../jquery/jquery-1.11.3.min.js"></script>
		<script src="../jquery/jquery-ui.js"></script>
		<script src="../jquery/datepicker-ja.js"></script>
		<script src="../script/logout.js"></script>
		<script src="../script/tabMenu.js"></script>
		<script src="../script/accordion.js"></script>
		<?php if($_SESSION["userinfo"]["authority"] == 2){?>
		<script src="../script/mainMenu-dialog.js"></script>
		<?php }?>
		<script>

		/*
		--------------------------------------
					タブ切り替え機能
		--------------------------------------
		*/

		//1ヶ月,2ヶ月,3ヶ月部分のタブ切り替えの初期表示を変数から受け取って表示する。
		jQuery( function() {
	   		jQuery( '#jquery-ui-tabs' ) . tabs( {
	        	active: <?php echo $model->getDispMonth();?>,
	    	} );
		} );


		  $(function() {

				  $("#datepicker").datepicker();
				  $("#datepicker").datepicker("option", "showOn", 'button');

		  });


		</script>

		<title>メインメニュー画面</title>
	</head>
	<body>
		<div class="container">
			<header class="box">
				<h1 class="title">勤怠管理システム</h1>
			</header>

			<div class="box width70 clearfix">
				<div class="userInfo float-left">
					<p>
						ユーザー名 : <?php echo $_SESSION['userinfo']['name'];?> /
						権限 : <?php if($_SESSION['userinfo']['authority'] == 2){?>
								管理者
							  <?php }else{?>
							  	一般ユーザー
							  <?php }?>
					</p>
				</div>
				<div class="userInfo float-right">
					<p><a href="../login/login.php?execute=logout" id="logoutLink">ログアウト</a></p>
				</div>
			</div>

			<div class="box menu"><!-- ヘッダーメニュー-->
				<?php if($_SESSION["userinfo"]["authority"] == 2){?>
					<ul id="dropmenu">
		 				<li><a href="">メニュー</a>
		   			 		<ul>
		    				</ul>
		 				 </li>
		  				<li><a href="../overallWorkTime/overallWorkTime.php">勤務時間表</a>
		   					<ul>
		   					</ul>
		 				</li>
		 				<li><a href="../settingHoliday/settingHoliday.php">休日設定</a>
		    				<ul>
		   					</ul>
		 				</li>
		  				<li><a href="#">ユーザー設定</a>
		   					<ul>
		     					<li><a href="../updateUser/updateUser.php">ユーザー設定変更</a></li>
		     					<li><a href="../insertUser/insertUser.php">ユーザー登録</a></li>
		   					</ul>
		  				</li>
		  				<li><a href="../settingRestTime/settingRestTime.php">休憩時間設定</a>
		   					<ul>
		   					</ul>
		  				</li>
					</ul>
				<?php }else{?>
					<ul id="dropmenu">
		 				<li style="width:50%"><a href="">メニュー</a>
		   			 		<ul>
		    				</ul>
		 				 </li>
		  				<li style="width:50%">
		  					<a href="../personalWorkTime/personalWorkTime.php?accountid=<?php echo $_SESSION["userinfo"]["accountid"];?>">
		  						勤務時間表
		  					</a>
		   					<ul>
		   					</ul>
		 				</li>
					</ul>
				<?php }?>
			</div>

			<div class="box main-container mainMenuCalendar clearfix">
				<br>
				<br>

				<?php if($_SESSION['userinfo']['authority'] == 1){?>
					<div align="center">

						<form action="" method="POST">
							<input type="submit" name="attendance" id="attendance" value="出勤">
							<input type="submit" name="clockout" id="clockout" value="退勤">
							<input type="hidden" name="accountid" value=<?php echo $_SESSION['userinfo']['accountid'];?>>
						</form>

					</div>
				<?php }?>

				<div id="jquery-ui-tabs">
    				<ul>
    					<li><a href="#jquery-ui-tabs-3">3ヶ月</a></li>
        				<li><a href="#jquery-ui-tabs-2">2ヶ月</a></li>
        				<li><a href="#jquery-ui-tabs-1">1ヶ月</a></li>
        				<form action="" method="POST">
        					<input type="submit" name="reset" value="本日の日付に戻る">
        				</form>
    				</ul>

						<?php if($_SESSION["userinfo"]["authority"] == 2){?>
						<dl id="acMenu">
							<dt>曜日一括設定</dt>
								<dd>
									<div id="holidaybox">
										<ul id="tabMenu" class="clearfix">
											<li><a href="#tabBox1">登録</a></li>
											<li><a href="#tabBox2">削除</a></li>
										</ul>

										<div class="holidayForm">

											<div id="tabBoxes">

												<div id="tabBox1">

													<form action="" method="POST">
														月<input type="checkbox" name="dayOfWeek[]" id="area1" value="1" >
														火<input type="checkbox" name="dayOfWeek[]" id="area2" value="2" >
														水<input type="checkbox" name="dayOfWeek[]" id="area3" value="3" >
														木<input type="checkbox" name="dayOfWeek[]" id="area4" value="4" >
														金<input type="checkbox" name="dayOfWeek[]" id="area5" value="5" >
														土 <input type="checkbox" name="dayOfWeek[]" id="area6" value="6" >
														日 <input type="checkbox" name="dayOfWeek[]" id="area7" value="0">


														<br>
														<br>

														<strong>期間選択：</strong>
														&nbsp;
														開始日付 ： <input type="date" id="startDay1" name="startWorkingday">
														終了日付 ： <input type="date" id="endDay1" name="endWorkingday">
														<br>
														<br>
														氏名：
														<select name="accountid">
											            	<?php foreach($model->getAccountList() as $id => $user):?>
																<option value="<?php echo $user["accountid"];?>"><?php echo $user["name"];?></option>
															<?php endforeach;?>
											            </select>
											        	&nbsp;
														 出勤時間：
														 <select name="workstarthour">
											            	<?php for($hour5=1; $hour5 <= 24 ;$hour5++){?>
												            	<option value="<?php echo $hour5;?>"><?php echo $hour5;?></option>
												            <?php }?>
											            </select>
														時
														<select name="workstartminute">
											            	<option value="00">00</option>
											            	<option value="10">10</option>
											            	<option value="20">20</option>
											            	<option value="30">30</option>
											            	<option value="40">40</option>
											            	<option value="50">50</option>
											            </select>
														 分
														 &nbsp;
														 退勤時間：
														 <select name="workendhour">
											            	<?php for($hour6=1; $hour6 <= 24 ;$hour6++){?>
												            	<option value="<?php echo $hour6;?>"><?php echo $hour6;?></option>
												            <?php }?>
											            </select>
														 時
														 <select name="workendminute">
											            	<option value="00">00</option>
											            	<option value="10">10</option>
											            	<option value="20">20</option>
											            	<option value="30">30</option>
											            	<option value="40">40</option>
											            	<option value="50">50</option>
											            </select>
														 分

											            <br>
											            <br>

														<input type="submit" id="allInsert" value="登録">
														<input type="hidden" name="execute" value="insertAll">
													</form>

												</div>
												<div id="tabBox2">
													<form action="" method="POST">
														月<input type="checkbox" id="week1" name="dayOfWeek[]" value="1" >
														火<input type="checkbox" id="week2" name="dayOfWeek[]" value="2" >
														水<input type="checkbox" id="week3" name="dayOfWeek[]" value="3" >
														木<input type="checkbox" id="week4" name="dayOfWeek[]" value="4" >
														金<input type="checkbox" id="week5" name="dayOfWeek[]" value="5" >
														土 <input type="checkbox" id="week6" name="dayOfWeek[]" value="6" >
														日 <input type="checkbox" id="week7" name="dayOfWeek[]" value="0">


														<br>
														<br>

														<strong>期間選択：</strong>
														&nbsp;
														開始日付 ： <input type="date" id="startDay2" name="startWorkingday">
														終了日付 ： <input type="date" id="endDay2" name="endWorkingday">
														<br>
														<br>
														氏名：
														<select name="accountid">
											            	<?php foreach($model->getAccountList() as $id => $user):?>
																<option value="<?php echo $user["accountid"];?>"><?php echo $user["name"];?></option>
															<?php endforeach;?>
											            </select>

											            <br>
											            <br>

														<input type="submit" id="allDelete" value="削除">
														<input type="hidden" name="execute" value="deleteAll">
													</form>

												</div>


											</div>

										</div>
									</div>

							</dd>

						</dl>
						<?php }?>

					<?php
						for($i=0; $i < count($model->getYear());$i++):
					?>

	    				<div id="jquery-ui-tabs-<?php echo $i+1;?>"><!-- $iヶ月分のカレンダーを表示 -->
							<?php for($j=0;	$j <= $i; $j++):?>
								<table>
									<tr>
										<th width="100%" colspan="7" style="background-color: #B3F8FA; text-align: center; font-weight: bold;">
										<?php if($j == 0):?>
											<a href="./mainMenu.php?changeTime=kyonen&year=<?php echo $model->getSelYear(0);?>&month=<?php echo $model->getSelMonth(0);?>&disp=<?php echo (2-$i);?>">
												&lt;&lt;
											</a>

											 &nbsp;&nbsp;

											 <a href="./mainMenu.php?changeTime=sengetu&year=<?php echo $model->getSelYear(0);?>&month=<?php echo $model->getSelMonth(0);?>&disp=<?php echo (2-$i);?>">
											 	&lt;
											 </a>

											 &nbsp;&nbsp;&nbsp;
										<?php endif;?>

											<?php echo $model->getSelYear($j); ?>年<?php echo $model->getSelMonth($j); ?>月

										<?php if($j == 0):?>
											&nbsp;&nbsp;

											<a href="./mainMenu.php?changeTime=yokugetu&year=<?php echo $model->getSelYear(0);?>&month=<?php echo $model->getSelMonth(0);?>&disp=<?php echo (2-$i);?>">
												&gt;
											</a>

											&nbsp;&nbsp;&nbsp;

											<a href="./mainMenu.php?changeTime=rainen&year=<?php echo $model->getSelYear(0);?>&month=<?php echo $model->getSelMonth(0);?>&disp=<?php echo (2-$i);?>">
												&gt;&gt;
											</a>
										<?php endif;?>
										<br>

										</th>
									</tr>
		    						<tr>
		        						<th>月</th>
		        						<th>火</th>
		       							<th>水</th>
		        						<th>木</th>
		        						<th>金</th>
		        						<th style="color: blue;">土</th>
		        						<th style="color: red;">日</th>
		    						</tr>

				    				<tr>
				    					<?php
				    						$cnt = 0;
				    					?>
		    							<?php foreach ($model->getSelCalendar($j) as $key => $value): ?>

										<?php
											$class = $model->setDateClass($model->getSelYear($j),$model->getSelMonth($j),$value['day']);
				        				?>

										<td class="<?php echo $class;?>">
				        					<?php $cnt++; ?>

				        					<div class="day-calendar" data-year="<?php echo $model->getSelYear($j);?>" data-month="<?php echo $model->getSelMonth($j);?>" data-day="<?php echo $value['day']; ?>">
				        						<?php echo $value['day']; ?>
				       						</div>

				        					<div class="work-calendar">

												<?php foreach($model->getSelWorkerList($j,$key) as $index => $info):?>
						        					<div id="work" style="color:<?php echo $info['code'];?>">

								        				<span id="change" data-name="<?php echo $info['name'];?>"
								        				 data-workplanid="<?php echo $info['workplanid'];?>"
								        				 data-year="<?php echo $model->getSelYear($j);?>"
								        				 data-month="<?php echo $model->getSelMonth($j);?>"
								        				 data-day="<?php echo $value['day']; ?>"
								        				 data-starthour="<?php echo createHour($info['workstarttime']);?>"
								        				 data-startminute="<?php echo createMinute($info['workstarttime']);?>"
								        				 data-endhour="<?php echo createHour($info['workendtime']);?>"
								        				 data-endminute="<?php echo createMinute($info['workendtime']);?>">

								        					<?php echo $info['name'];?>

								        				</span>

								        				<span id="time">
									        				<?php echo createTimeFormat($info['workstarttime']);?>
									        				<?php if($info['workstarttime'] !=""):?>
									        				 ~
									        				<?php endif;?>
									        				<?php echo createTimeFormat($info['workendtime']);?>
								        				</span>

								        				<span id="position">
								        					<?php echo getFirstStr($info['p-name']); ?>
								        				</span>

						        					</div>
						        				<?php endforeach;?>

				        					</div>

				        				</td>


				    					<?php if ($cnt == 7): ?>
				    				</tr>

				    				<tr>
				    					<?php $cnt = 0; ?>

				   						<?php endif; ?>
				    					<?php
				    						endforeach;
				    					?>
				   				 	</tr>
								</table>
							<?php endfor;?>
						</div>

					<?php endfor;?>
				</div><!-- jquery-ui-tabs -->

			</div><!-- box main-container  -->


<?php if($_SESSION["userinfo"]["authority"] == 2){?>
<div id="jquery-ui-dialog" title="勤務登録">
    <form method="post" id="insertForm">
    <fieldset>
        <p>
            <label for="jquery-ui-dialog-form-name">名前</label>
            <select name="jquery-ui-dialog-form-name" id="jquery-ui-dialog-form-name" class="text ui-widget-content ui-corner-all" />
            	<?php foreach($model->getAccountList() as $num => $ac):?>
					<option value="<?php echo $ac["accountid"];?>"><?php echo $ac["name"];?></option>
				<?php endforeach;?>
            </select>
        </p>

        <p>
            <label for="jquery-ui-dialog-form-hour">出勤時間</label>
            <select name="jquery-ui-dialog-form-hour" id="jquery-ui-dialog-form-hour" class="text ui-widget-content ui-corner-all" />
            <?php for($hour1=1; $hour1 <= 24 ;$hour1++){?>
            	<option value="<?php echo $hour1;?>"><?php echo $hour1;?></option>
            <?php }?>


            </select>
   			時
   			<select name="jquery-ui-dialog-form-minute" id="jquery-ui-dialog-form-minute" class="text ui-widget-content ui-corner-all" />
            	<option value="00">00</option>
            	<option value="10">10</option>
               	<option value="20">20</option>
				<option value="30">30</option>
				<option value="40">40</option>
				<option value="50">50</option>
            </select>
			 分
        </p>

        <p>
            <label for="jquery-ui-dialog-form-endhour">退勤時間</label>
            <select name="jquery-ui-dialog-form-endhour" id="jquery-ui-dialog-form-endhour" class="text ui-widget-content ui-corner-all" />
            	<?php for($hour2=1; $hour2 <= 24 ;$hour2++){?>
	            	<option value="<?php echo $hour2;?>"><?php echo $hour2;?></option>
	            <?php }?>
            </select>
   			時
   			<select name="jquery-ui-dialog-form-endminute" id="jquery-ui-dialog-form-endminute" class="text ui-widget-content ui-corner-all" />
            	<option value="00">00</option>
            	<option value="10">10</option>
               	<option value="20">20</option>
				<option value="30">30</option>
				<option value="40">40</option>
				<option value="50">50</option>
            </select>
			 分
        </p>
        <p>
        	<label for="jquery-ui-dialog-form-position">担当</label>
        	<select name="jquery-ui-dialog-form-position" id="jquery-ui-dialog-form-position" class="text ui-widget-content ui-corner-all" />
				<?php foreach($model->getPositionList() as $p):?>
					<option value="<?php echo $p["positionid"];?>"><?php echo $p["p-name"];?></option>
				<?php endforeach;?>
        	</select>
        </p>
        <input type="hidden" name="year" id="year">
        <input type="hidden" name="month" id="month">
        <input type="hidden" name="day" id="day">
    </fieldset>
    </form>
</div>

<div id="jquery-ui-dialog2" title="出勤情報修正">
    <form>
    <fieldset>
        <p class="changename"></p>
        <p>
        	<label for="jquery-ui-dialog-form-date2">出勤日</label>
        	<input type="text" name="updateDate" id="datepicker" value="">
        </p>
        <p>
            <label for="jquery-ui-dialog-form-hour2">出勤時間</label>
            <select name="jquery-ui-dialog-form-hour2" id="jquery-ui-dialog-form-hour2" class="text ui-widget-content ui-corner-all" />
            	<?php for($hour3=1; $hour3 <= 24 ;$hour3++){?>
	            	<option value="<?php echo $hour3;?>"><?php echo $hour3;?></option>
	            <?php }?>
            </select>
   			時
   			<select name="jquery-ui-dialog-form-minute2" id="jquery-ui-dialog-form-minute2" class="text ui-widget-content ui-corner-all" />
            	<option value="00">00</option>
            	<option value="10">10</option>
               	<option value="20">20</option>
				<option value="30">30</option>
				<option value="40">40</option>
				<option value="50">50</option>
            </select>
			 分
        </p>

        <p>
            <label for="jquery-ui-dialog-form-endhour2">退勤時間</label>
            <select name="jquery-ui-dialog-form-endhour2" id="jquery-ui-dialog-form-endhour2" class="text ui-widget-content ui-corner-all" />
            	<?php for($hour4=1; $hour4 <= 24 ;$hour4++){?>
	            	<option value="<?php echo $hour4;?>"><?php echo $hour4;?></option>
	            <?php }?>
            </select>
   			時
   			<select name="jquery-ui-dialog-form-endminute2" id="jquery-ui-dialog-form-endminute2" class="text ui-widget-content ui-corner-all" />
            	<option value="00">00</option>
				<option value="10">10</option>
				<option value="20">20</option>
				<option value="30">30</option>
				<option value="40">40</option>
				<option value="50">50</option>
            </select>
			 分
        </p>

    </fieldset>
    	<input type="hidden" name="workplanid" id=workplanid>
    	 <input type="hidden" name="year2" id="year2">
        <input type="hidden" name="month2" id="month2">
        <input type="hidden" name="day2" id="day2">
    </form>
</div>
<?php }?>

			<footer class="box footer">
				<p>Copyright © 2010-2015 FusionOne Co.,Ltd. All Rights Reserved.</p>
			</footer>

		</div>	<!-- container -->
	</body>
</html>