<!DOCTYPE html>
<html lang="ja">
	<head>
		<meta charset="UTF-8">
		<link rel="stylesheet" href="../css/design.css">
		<link rel="stylesheet" href="../css/content.css">
		<link rel="stylesheet" href="../jquery/jquery-ui.css">
		<script src="../jquery/jquery-1.11.3.min.js"></script>
		<script src="../jquery/jquery-ui.js"></script>
		<script>

		/*
		--------------------------------------
					タブ切り替え機能
		--------------------------------------
		*/

		//1ヶ月,2ヶ月,3ヶ月部分のタブ切り替えの初期表示を変数から受け取って表示する。
		jQuery( function() {
	   		jQuery( '#jquery-ui-tabs' ) . tabs( {
	        	active: <?php echo $model->getDispMonth();?>,
	    	} );
		} );

		 $(function(){
		        $("#tabMenu li a").on("click", function() {
		            $("#tabBoxes div").hide();
		            $($(this).attr("href")).fadeToggle();
		        });
		        return false;
		    });

	    $(function(){
	        $("#acMenu dt").on("click", function() {
	            $(this).next().slideToggle();
	        });
	    });

		jQuery( function() {
		    jQuery( '.day-calendar' ) . click( function() {
		    	console.log($(this).data('year'));
		    	console.log($(this).data('month'));
				console.log($(this).data('day'));
				$('#year').val($(this).data('year'));
				$('#month').val($(this).data('month'));
				$('#day').val($(this).data('day'));

		        jQuery( '#jquery-ui-dialog' ) . dialog( 'open' );
		    } );
		    var date = 250;
		    var name = jQuery( '#jquery-ui-dialog-form-name' );
		    var hour = jQuery( '#jquery-ui-dialog-form-hour' );
		    var minute = jQuery( '#jquery-ui-dialog-form-minute' );
		    var endhour = jQuery( '#jquery-ui-dialog-form-endhour' );
		    var endminute = jQuery( '#jquery-ui-dialog-form-endminute' );

		    jQuery( '#jquery-ui-dialog' ) . dialog( {
		        autoOpen: false,
		        width: 350,
		        show: 'explode',
		        hide: 'explode',
		        modal: true,
		        buttons: {
		            '登録': function() {
		                if ( name . val() || hour . val() ) {

		                	$.ajax({
			  				      type: 'POST',
			  				      url:'test.php',
			  				      data:{
									"name": $('select[name="jquery-ui-dialog-form-name"]').val(),
			  						"insertYear": $(':hidden[name="year"]').val(),
			  						"insertMonth": $(':hidden[name="month"]').val(),
			  						"insertDay": $(':hidden[name="day"]').val()

			  				      },
			  				      success:function(data) {
			  				        alert("登録しました。");
			  				      },
			  				      error:function(XMLHttpRequest, textStatus, errorThrown) {

			  				   	 　}
			  				 });

		                    jQuery( 'div.work-calendar' ) . append(
		                        '<div id="work"><span id="change" data-name=name>' + name . val() +
		                        '</span> ' + hour . val() +
		                        ':' + minute . val() + '~' + endhour . val() +
		                        ':' + endminute . val() + '&nbsp;講  </div>'
		                    );
		                    jQuery( this ).dialog( 'close' );
		                }
		                jQuery( this ) . dialog( 'close' );
		            },
		            'キャンセル': function() {
		                jQuery( this ) . dialog( 'close' );
		            },
		        }
		    } );
		} );

		jQuery( function() {
		    jQuery( 'span#change' ) . click( function() {
			    $('.changename').text($('span#change').data('name'));
		        jQuery( '#jquery-ui-dialog2' ) . dialog( 'open' );
		    } );
		    var hour2 = jQuery( '#jquery-ui-dialog-form-hour2' );
		    var minute2 = jQuery( '#jquery-ui-dialog-form-minute2' );
		    var endhour2 = jQuery( '#jquery-ui-dialog-form-endhour2' );
		    var endminute2 = jQuery( '#jquery-ui-dialog-form-endminute2' );
		    jQuery( '#jquery-ui-dialog2' ) . dialog( {
		        autoOpen: false,
		        width: 350,
		        show: 'explode',
		        hide: 'explode',
		        modal: true,
		        buttons: {
	            '変更': function() {
	                if ( hour2 . val() ) {
	                    jQuery( 'span#time' ) . text(
	    	                hour2 . val() + ':' + minute2 . val() +
	    	                '~' + endhour2 . val() + ':' + endminute2 . val()
	                    );
	                    jQuery( this ).dialog( 'close' );
	                }
	                jQuery( this ) . dialog( 'close' );
	            },
	            '削除': function() {
	            	$("div#work").remove();
	                jQuery( this ) . dialog( 'close' );
	            },
	            'キャンセル': function() {
	                jQuery( this ) . dialog( 'close' );
	            },
	        }
	    } );
	} );
		</script>
		<style>

			#jquery-ui-tabs {
   				font-size: 16px;
			}

			#jquery-ui-tabs ul li{
				float: right;
			}

		</style>
		<title>メインメニュー画面</title>
	</head>
	<body>
		<div class="container">
			<header class="box">
				<h1 class="title">勤怠管理システム</h1>
			</header>

			<div class="box width70 clearfix">
				<div class="userInfo float-left">
					<p>ユーザー名 : admin / 権限 : 管理者</p>
				</div>
				<div class="userInfo float-right">
					<p><a href="../login/login.php">ログアウト</a></p>
				</div>
			</div>

			<div class="box menu"><!-- ヘッダーメニュー-->
				<ul id="dropmenu">
	 				<li><a href="">メニュー</a>
	   			 		<ul>
	    				</ul>
	 				 </li>
	  				<li><a href="../overallWorkTime/overallWorkTime.html">勤務時間表</a>
	   					<ul>
	   					</ul>
	 				</li>
	 				<li><a href="../settingHoliday/settingHoliday.html">休日設定</a>
	    				<ul>
	   					</ul>
	 				</li>
	  				<li><a href="#">ユーザー設定</a>
	   					<ul>
     					 	<li><a href="../changePassword/changePassword.html">パスワード変更</a></li>
	     					<li><a href="../updateUser/updateUser.php">ユーザー設定変更</a></li>
	     					<li><a href="../insertUser/insertUser.html">ユーザー登録</a></li>
	   					</ul>
	  				</li>
	  				<li><a href="../settingRestTime/settingRestTime.html">休憩時間設定</a>
	   					<ul>
	   					</ul>
	  				</li>
				</ul>
			</div>

			<div class="box main-container mainMenuCalendar clearfix">
				<br>
				<br>

				<div id="jquery-ui-tabs">
    				<ul>
    					<li><a href="#jquery-ui-tabs-3">3ヶ月</a></li>
        				<li><a href="#jquery-ui-tabs-2">2ヶ月</a></li>
        				<li><a href="#jquery-ui-tabs-1">1ヶ月</a></li>
        				<form action="" method="POST">
        					<input type="submit" name="reset" value="本日の日付に戻る">
        				</form>
    				</ul>


						<dl id="acMenu">
							<dt>曜日一括設定</dt>
								<dd>
									<div id="holidaybox">
										<ul id="tabMenu" class="clearfix">
											<li><a href="#tabBox1">登録</a></li>
											<li><a href="#tabBox2">削除</a></li>
										</ul>

										<div class="holidayForm">

											<div id="tabBoxes">

												<div id="tabBox1">
													月<input type="checkbox" name="dayOfWeek" value="monday" >
													火<input type="checkbox" name="dayOfWeek" value="tuesday" >
													水<input type="checkbox" name="dayOfWeek" value="wednesday" >
													木<input type="checkbox" name="dayOfWeek" value="thursday" >
													金<input type="checkbox" name="dayOfWeek" value="fryday" >
													土 <input type="checkbox" name="dayOfWeek" value="saturday" >
													日 <input type="checkbox" name="dayOfWeek" value="sunday">

													<br>
													<br>

													<strong>期間選択：</strong>
													&nbsp;
													開始日付 ： <input type="date" name="startHoliday">
													終了日付 ： <input type="date" name="endHoliday">
													<br>
													<br>
													氏名：
													<select name="nameSel">
										            	<option value="神田太郎">神田太郎</option>
										            	<option value="東京太郎">東京太郎</option>
										            	<option value="秋葉流">秋葉流</option>
										            </select>
										        	&nbsp;
													 出勤時間：
													 <select name="startWorkHour">
										            	<option value="8">8</option>
										            	<option value="9">9</option>
										            	<option value="10">10</option>
										            </select>
													時
													<select name="startWorkMinute">
										            	<option value="00">00</option>
										            	<option value="10">10</option>
										            	<option value="20">20</option>
										            	<option value="30">30</option>
										            	<option value="40">40</option>
										            	<option value="50">50</option>
										            </select>
													 分
													 &nbsp;
													 退勤時間：
													 <select name="startWorkHour">
										            	<option value="18">18</option>
										            	<option value="19">19</option>
										            	<option value="20">20</option>
										            </select>
													 時
													 <select name="startWorkMinute">
										            	<option value="00">00</option>
										            	<option value="10">10</option>
										            	<option value="20">20</option>
										            	<option value="30">30</option>
										            	<option value="40">40</option>
										            	<option value="50">50</option>
										            </select>
													 分

										            <br>
										            <br>

													<input type="submit" value="登録">

												</div>
												<div id="tabBox2">
														月<input type="checkbox" name="dayOfWeek" value="monday" >
													火<input type="checkbox" name="dayOfWeek" value="tuesday" >
													水<input type="checkbox" name="dayOfWeek" value="wednesday" >
													木<input type="checkbox" name="dayOfWeek" value="thursday" >
													金<input type="checkbox" name="dayOfWeek" value="fryday" >
													土 <input type="checkbox" name="dayOfWeek" value="saturday" >
													日 <input type="checkbox" name="dayOfWeek" value="sunday">

													<br>
													<br>

													<strong>期間選択：</strong>
													&nbsp;
													開始日付 ： <input type="date" name="startHoliday">
													終了日付 ： <input type="date" name="endHoliday">
													<br>
													<br>
													氏名：
													<select name="nameSel">
										            	<option value="神田太郎">神田太郎</option>
										            	<option value="東京太郎">東京太郎</option>
										            	<option value="秋葉流">秋葉流</option>
										            </select>
										        	&nbsp;
													 出勤時間：
													 <select name="startWorkHour">
										            	<option value="8">8</option>
										            	<option value="9">9</option>
										            	<option value="10">10</option>
										            </select>
													時
													<select name="startWorkMinute">
										            	<option value="00">00</option>
										            	<option value="10">10</option>
										            	<option value="20">20</option>
										            	<option value="30">30</option>
										            	<option value="40">40</option>
										            	<option value="50">50</option>
										            </select>
													 分
													 &nbsp;
													 退勤時間：
													 <select name="startWorkHour">
										            	<option value="18">18</option>
										            	<option value="19">19</option>
										            	<option value="20">20</option>
										            </select>
													 時
													 <select name="startWorkMinute">
										            	<option value="00">00</option>
										            	<option value="10">10</option>
										            	<option value="20">20</option>
										            	<option value="30">30</option>
										            	<option value="40">40</option>
										            	<option value="50">50</option>
										            </select>
													 分

										            <br>
										            <br>

													<input type="submit" value="削除">

												</div>


											</div>

										</div>
									</div>

							</dd>

						</dl>

					<?php
						for($i=0; $i < count($model->getYear());$i++):
					?>

	    				<div id="jquery-ui-tabs-<?php echo $i+1;?>"><!-- $iヶ月分のカレンダーを表示 -->
							<?php for($j=0;	$j <= $i; $j++):?>
								<table>
									<tr>
										<th width="100%" colspan="7" style="background-color: #B3F8FA; text-align: center; font-weight: bold;">
										<?php if($j == 0):?>
											<a href="./mainMenu.php?changeTime=kyonen&year=<?php echo $model->getSelYear(0);?>&month=<?php echo $model->getSelMonth(0);?>&disp=<?php echo (2-$i);?>">
												&lt;&lt;
											</a>

											 &nbsp;&nbsp;

											 <a href="./mainMenu.php?changeTime=sengetu&year=<?php echo $model->getSelYear(0);?>&month=<?php echo $model->getSelMonth(0);?>&disp=<?php echo (2-$i);?>">
											 	&lt;
											 </a>

											 &nbsp;&nbsp;&nbsp;
										<?php endif;?>

											<?php echo $model->getSelYear($j); ?>年<?php echo $model->getSelMonth($j); ?>月

										<?php if($j == 0):?>
											&nbsp;&nbsp;

											<a href="./mainMenu.php?changeTime=yokugetu&year=<?php echo $model->getSelYear(0);?>&month=<?php echo $model->getSelMonth(0);?>&disp=<?php echo (2-$i);?>">
												&gt;
											</a>

											&nbsp;&nbsp;&nbsp;

											<a href="./mainMenu.php?changeTime=rainen&year=<?php echo $model->getSelYear(0);?>&month=<?php echo $model->getSelMonth(0);?>&disp=<?php echo (2-$i);?>">
												&gt;&gt;
											</a>
										<?php endif;?>
										</th>
									</tr>
		    						<tr>
		        						<th style="color: red;">日</th>
		        						<th>月</th>
		        						<th>火</th>
		       							<th>水</th>
		        						<th>木</th>
		        						<th>金</th>
		        						<th style="color: blue;">土</th>
		    						</tr>

				    				<tr>
				    					<?php
				    						$cnt = 0;
				    					?>
		    							<?php foreach ($model->getSelCalendar($j) as $key => $value): ?>

										<?php

											//現在の日にちのカレンダーかつ,日付が一致しループの一回目の場合、本日日付のカレンダーの色を変更する

											if($model->getYear() == $model->getToday() && $model->getMonth() == $month && $value['day'] == $today && $calCnt == 0){
												$stylecolor="#EEF1F1";
											}else{
												$stylecolor="#FFFFFF";
											}

											//土日の色を変更する

				        					if($cnt == 0){
												$fontcolor="red";
				    						}else if($cnt == 6){
												$fontcolor="blue";
				    						}else{
				    							$fontcolor="#000000";
				    						}
				        				?>

										<td style="background-color: <?php echo $stylecolor;?>; color:<?php echo $fontcolor;?>;">
				        					<?php $cnt++; ?>

				        					<div class="day-calendar" data-year="<?php echo $model->getSelYear($j);?>" data-month="<?php echo $model->getSelMonth($j);?>" data-day="<?php echo $value['day']; ?>">
				        						<?php echo $value['day']; ?>
				       						</div>
				        					<?php if($value['day'] == 8){?>
				        					<div class="work-calendar">
				        						<div id="work"><span id="change" data-name="神田太郎">神田太郎</span>  <span id="time">12:00~18:00</span>  講</div>
				        					</div>
				        					<?php }?>
				        				</td>


				    					<?php if ($cnt == 7): ?>
				    				</tr>

				    				<tr>
				    					<?php $cnt = 0; ?>

				   						<?php endif; ?>
				    					<?php
				    						endforeach;
				    					?>
				   				 	</tr>
								</table>
							<?php endfor;?>
						</div>

					<?php endfor;?>
				</div><!-- jquery-ui-tabs -->

			</div><!-- box main-container  -->



<div id="jquery-ui-dialog" title="勤務登録">
    <form method="post" id="insertForm">
    <fieldset>
        <p>
            <label for="jquery-ui-dialog-form-name">名前</label>
            <select name="jquery-ui-dialog-form-name" id="jquery-ui-dialog-form-name" class="text ui-widget-content ui-corner-all" />
            	<option value="神田太郎">神田太郎</option>
            	<option value="東京太郎">東京太郎</option>
            	<option value="秋葉流">秋葉流</option>
            </select>
        </p>

        <p>
            <label for="jquery-ui-dialog-form-hour">出勤時間</label>
            <select name="jquery-ui-dialog-form-hour" id="jquery-ui-dialog-form-hour" class="text ui-widget-content ui-corner-all" />
            	<option value="1">1</option>
            	<option value="2">2</option>
            	<option value="3">3</option>
            	<option value="4">4</option>
            </select>
   			時
   			<select name="jquery-ui-dialog-form-minute" id="jquery-ui-dialog-form-minute" class="text ui-widget-content ui-corner-all" />
            	<option value="00">00</option>
            	<option value="30">30</option>
            </select>
			 分
        </p>

        <p>
            <label for="jquery-ui-dialog-form-endhour">退勤時間</label>
            <select name="jquery-ui-dialog-form-endhour" id="jquery-ui-dialog-form-endhour" class="text ui-widget-content ui-corner-all" />
            	<option value="17">17</option>
            	<option value="18">18</option>
            	<option value="19">19</option>
            	<option value="20">20</option>
            </select>
   			時
   			<select name="jquery-ui-dialog-form-endminute" id="jquery-ui-dialog-form-endminute" class="text ui-widget-content ui-corner-all" />
            	<option value="00">00</option>
            	<option value="30">30</option>
            </select>
			 分
        </p>
        <input type="hidden" name="year" id="year">
        <input type="hidden" name="month" id="month">
        <input type="hidden" name="day" id="day">
    </fieldset>
    </form>
</div>

<div id="jquery-ui-dialog2" title="出勤情報修正">
    <form>
    <fieldset>
        <p class="changename"></p>
        <p>
            <label for="jquery-ui-dialog-form-hour2">出勤時間</label>
            <select name="jquery-ui-dialog-form-hour2" id="jquery-ui-dialog-form-hour2" class="text ui-widget-content ui-corner-all" />
            	<option value="1">1</option>
            	<option value="2">2</option>
            	<option value="3">3</option>
            	<option value="4">4</option>
            </select>
   			時
   			<select name="jquery-ui-dialog-form-minute2" id="jquery-ui-dialog-form-minute2" class="text ui-widget-content ui-corner-all" />
            	<option value="00">00</option>
            	<option value="30">30</option>
            </select>
			 分
        </p>

        <p>
            <label for="jquery-ui-dialog-form-endhour2">退勤時間</label>
            <select name="jquery-ui-dialog-form-endhour2" id="jquery-ui-dialog-form-endhour2" class="text ui-widget-content ui-corner-all" />
            	<option value="17">17</option>
            	<option value="18">18</option>
            	<option value="19">19</option>
            	<option value="20">20</option>
            </select>
   			時
   			<select name="jquery-ui-dialog-form-endminute2" id="jquery-ui-dialog-form-endminute2" class="text ui-widget-content ui-corner-all" />
            	<option value="00">00</option>
            	<option value="30">30</option>
            </select>
			 分
        </p>

    </fieldset>
    </form>
</div>

			<footer class="box footer">
				<p>Copyright © 2010-2015 FusionOne Co.,Ltd. All Rights Reserved.</p>
			</footer>

		</div>	<!-- container -->
	</body>
</html>