<!DOCTYPE html>
<html lang="ja">
	<head>
		<meta charset="UTF-8">
		<link rel="stylesheet" href="../css/design.css">
		<link rel="stylesheet" href="../css/content.css">
		<link rel="stylesheet" href="../jquery/jquery-ui.css">
		<link rel="stylesheet" href="../jquery/spectrum.css">
		<title>ユーザー設定変更画面</title>
		<script type="text/javascript" src="../jquery/jquery-1.11.3.min.js"></script>
		<script src="../jquery/jquery-ui.js"></script>
		<script src="../jquery/spectrum.js"></script>
		<script type="text/javascript" src="../script/logout.js"></script>
		<script type="text/javascript" src="../script/eventList.js"></script>
	</head>
	<body>
		<div class="container">
			<header class="box">
				<h1 class="title">勤怠管理システム</h1>
			</header>

			<div class="box width70 clearfix">
				<div class="userInfo float-left">
					<p>
						ユーザー名 : <?php echo $_SESSION['userinfo']['name'];?> /
						権限 : <?php if($_SESSION['userinfo']['authority'] == 2){?>
								管理者
							  <?php }else{?>
							  	一般ユーザー
							  <?php }?>
					</p>
				</div>
				<div class="userInfo float-right">
					<p><a href="../login/login.php?execute=logout" id="logoutLink">ログアウト</a></p>
				</div>
			</div>

			<div class="box menu"><!-- ヘッダーメニュー-->
				<ul id="dropmenu">
	 				<li><a href="../mainMenu/mainMenu.php">メニュー</a>
	   			 		<ul>
	    				</ul>
	 				 </li>
	  				<li><a href="../overallWorkTime/overallWorkTime.php">勤務時間表</a>
	   					<ul>
	   					</ul>
	 				</li>
	 				<li><a href="../settingHoliday/settingHoliday.php">休日設定</a>
	    				<ul>
	   					</ul>
	 				</li>
	  				<li><a href="#">管理設定</a>
	   					<ul>
	     					<li><a href="./updateUser.php">ユーザー設定変更</a></li>
	     					<li><a href="../insertUser/insertUser.php">ユーザー登録</a></li>
	     					<li><a href="./eventList.php">セミナー一覧</a></li>
	     					<li><a href="../insertEvent/insertEvent.php">セミナー登録</a></li>
	   						<li><a href="../managementElements/managementElements.php">各種設定一覧</a></li>
	   					</ul>
	  				</li>
	  				<li><a href="../settingRestTime/settingRestTime.php">休憩時間設定</a>
	   					<ul>
	   					</ul>
	  				</li>
				</ul>
			</div>

			<div class="box main-container">

					<table align="center" border="2">
						<tr>
							<th colspan = "6">
							セミナー 一覧
							</th>
						</tr>
						<tr class="record">
							<th>セミナー名</th>
							<th>略名</th>
							<th>表示色</th>
							<th>変更/削除</th>
						</tr>
					<?php foreach((array)$model->getEventList() as $num => $value):?>
						<tr>

								<td>
									<span id="eventName<?php echo $num;?>"><?php echo $value["eventName"];?></span>
								</td>
								<td>
									<span id="<?php echo $num;?>"><?php echo $value["shortName"];?></span>
								</td>
								<td>
									<span class="eventSquare" id="eventColor<?php echo $num;?>" style="background-color: <?php echo $value["color"];?>">
									</span>
								</td>

								<td>
									<input type="button" value="変更" class="update"
												data-execute="update" data-eventid="<?php echo $value["eventid"];?>"
												data-eventname="<?php echo $value["eventName"];?>"
												data-shortname="<?php echo $value["shortName"];?>"
												data-color="<?php echo $value["color"];?>"
												data-index="<?php echo $num;?>">
									<form action = "" method="POST" style="display:inline;">
									<input type="submit" value="削除" class="delete"
												data-execute="delete" >
									<input type="hidden" name="eventid" value="<?php echo $value["eventid"];?>">
									<input type="hidden" name="execute" value="delete">

									</form>



								</td>


						</tr>
					<?php endforeach;?>
					</table>




			<footer class="box footer">
				<p>Copyright © 2010-2015 FusionOne Co.,Ltd. All Rights Reserved.</p>
			</footer>

		</div>

		<div id="jquery-ui-dialog" title="セミナー情報変更">
		    <form method="post" id="insertEventForm">
		    <fieldset>
		        <p>
		            <label for="jquery-ui-dialog-form-name">セミナー名：</label>
		            <input type="text" name="eventName" id="eventNameForm" maxlength="20">
		        </p>

		        <p>
		            <label for="jquery-ui-dialog-form-shortName">セミナー略名：</label>
		           	<input type="text" name="shortName"  id="shortNameForm" maxlength="3">
		        </p>

		        <p>
		            <label for="jquery-ui-dialog-form-color">表示色</label>
		            <input type="color" name="color" id="colorForm">

		        </p>

		        <input type="hidden" name="eventid" id="eventid">
		        <input type="hidden" name="oldName" id="oldName">
		        <input type="hidden" name="oldShortName" id="oldShortName">
		        <input type="hidden" name="oldColor" id="oldColor">

		    </fieldset>
		    </form>
		</div>

		<div id="jquery-ui-dialog2" title="セミナー情報変更">
		    <form>
		    <fieldset>
		        <p>
		        	以下のセミナー情報を変更しました
		        </p>

		        <table id="changeEventTable">
		        	<tr>
		        		<th class="eventTableTitle"></th>
		        		<th class="eventTableTitle">変更前</th>
		        		<th class="eventTableTitle">変更後</th>
		        	</tr>
		        	<tr>
		        		<th>
		        			セミナー名
		        		</th>
		        		<td>
		        			<span id="oldEventNameDisp"></span>
		        		</td>
		        		<td>
		        			<span id="eventNameDisp"></span>
		        		</td>
		        	</tr>

		        	<tr>
		        		<th>
		        			セミナー略名
		        		</th>
		        		<td>
		        			<span id="oldShortNameDisp"></span>
		        		</td>
		        		<td>
		        			<span id="shortNameDisp"></span>
		        		</td>
		        	</tr>
		        	<tr>
		        		<th>
		        			表示色
		        		</th>
		        		<td>
		        			<span class="eventSquare" id="oldColorDisp"></span>
		        		</td>
		        		<td>
		        			<span class="eventSquare" id="colorDisp"></span>
		        		</td>
		        	</tr>
		        </table>



		    </fieldset>

		    </form>
		</div>

	</body>
</html>