<?php
$workdata = $model->getWorkData();
$restdata = $model->getRestData();
$statusinfo = $model->getStatusInfo();
$workstatus = $model->getWorkStatus();
$sum = $model->getSum();

//var_dump($restdata);
//var_dump($workdata);
?>
<!DOCTYPE html>
<html lang="ja">
	<head>
		<meta charset="UTF-8">
		<link rel="stylesheet" href="../css/design.css">
		<link rel="stylesheet" href="../css/content.css">
		<link rel="stylesheet" href="../jquery/jquery-ui.css">
		<script src="../jquery/jquery-1.11.3.min.js"></script>
		<script src="../jquery/jquery-ui.js"></script>
		<script src="../jquery/datepicker-ja.js"></script>
		<script src="../script/workTime.js"></script>

		<title>勤務時間表(個人)画面</title>
	</head>
	<body>
		<div class="container">
			<header class="box">
				<h1 class="title">勤怠管理システム</h1>
			</header>

			<div class="box width70 clearfix">

				<div class="userInfo float-left">
					<p>
						ユーザー名 : <?php echo $_SESSION['userinfo']['name'];?> /
						権限 : <?php if($_SESSION['userinfo']['authority'] == 2){?>
								管理者
							  <?php }else{?>
							  	一般ユーザー
							  <?php }?>
					</p>
				</div>

				<div class="userInfo float-right">
					<p><a href="../login/login.php">ログアウト</a></p>
				</div>

			</div>

			<div class="box menu"><!-- ヘッダーメニュー-->
				<?php if($_SESSION["userinfo"]["authority"] == 2){?>
					<ul id="dropmenu">
		 				<li><a href="../mainMenu/mainMenu.php">メニュー</a>
		   			 		<ul>
		    				</ul>
		 				 </li>
		  				<li><a href="../overallWorkTime/overallWorkTime.php">勤務時間表</a>
		   					<ul>
		   					</ul>
		 				</li>
		 				<li><a href="../settingHoliday/settingHoliday.php">休日設定</a>
		    				<ul>
		   					</ul>
		 				</li>
		  				<li><a href="#">管理設定</a>
		   					<ul>
		     					<li><a href="../updateUser/updateUser.php">ユーザー設定変更</a></li>
		     					<li><a href="../insertUser/insertUser.php">ユーザー登録</a></li>
		     					<li><a href="../eventList/eventList.php">セミナー一覧</a></li>
	     						<li><a href="../insertEvent/insertEvent.php">セミナー登録</a></li>
		   						<li><a href="../managementElements/managementElements.php">各種設定一覧</a></li>
		   					</ul>
		  				</li>
		  				<li><a href="../settingRestTime/settingRestTime.php">休憩時間設定</a>
		   					<ul>
		   					</ul>
		  				</li>
					</ul>
				<?php }else{?>
					<ul id="dropmenu">
		 				<li style="width:50%"><a href="../mainMenu/mainMenu.php">メニュー</a>
		   			 		<ul>
		    				</ul>
		 				</li>
		  				<li style="width:50%">
		  					<a href="../personalWorkTime/personalWorkTime.php?accountid=<?php echo $_SESSION["userinfo"]["accountid"];?>">
		  						勤務時間表
		  					</a>
		   					<ul>
		   					</ul>
		 				</li>
					</ul>
				<?php }?>
			</div>

			<div class="box main-container">
				<div class="workTime">
					<p>条件検索</p>
					<div class="selectbox">
					<form action="personalWorkTime.php" method="POST">
						<table>
							<tr>

								<!--表示非表示の切り替え　年次-->
								<?php $yearList = createYearSet();?>
								<td id="formYear">
									<select name="year">
										<option value="<?=date("Y")?>"><?=date("Y")?></option>
										<?php for($a=0; $a<count($yearList); $a++){?>
										<option value="<?=$yearList[$a]?>"><?=$yearList[$a]?></option>
										<?php }?>
									</select> 年
								</td>

								<!--表示非表示の切り替え　月次-->
						       	<td id="formMonth">
									<input type="month" name="month" placeholder="例)2014-01" value="<?=$model->getMonth();?>">
								</td>

								<!--表示非表示の切り替え　期間-->
								<td id="formPeriod">
									 開始期間
									<input type="month" name="startDay" placeholder="例)2014-06"
											size="15" value="<?=$model->getStartDay();?>">
									 ～ 終了期間
									<input type="month" name="endDay" placeholder="例)2014-09"
											size="15" value="<?=$model->getEndDay();?>">
								</td>
							</tr>
						</table>

						表示時間:<?php $work = $model->getWork();?>
            			<label><input type="radio" name="work" value="year" onclick="formChange();"
            				<?php if($work == 'year'){echo 'checked';}?>>年次</label>

            			<label><input type="radio" name="work" value="month" onclick="formChange();"
							<?php if($work == 'month'){echo ' checked';}?>>月次</label>

           				<label><input type="radio" name="work" value="period" onclick="formChange();"
            				<?php if($work == 'period'){echo ' checked';}?>>期間</label>

						&nbsp;&nbsp;&nbsp;<input type="submit" name="execute" value="表示">
						<input type="hidden" name="accountid" value="<?=$model->getAccountId();?>">
					</div>
					<br>
					表示期間 : <?=$model->getInfomation();?>

					<?php
					$s=0;
					for($v=0; $v<count($workdata); $v++){?>
						<table class="worksheet">
							<caption><?=$model->getName();?>出勤表</caption>
								<tr class="record">
									<td>日付</td>
									<td>曜日</td>
									<td>出勤</td>
									<td>退勤</td>
									<td>休憩時間</td>
									<td>実働時間</td>
									<td>ステータス</td>
									<td>備考欄</td>
								</tr>

								<?php
									$week = array('日','月','火','水','木','金','土');
									for($i=0;$i<count($workdata[$v]); $i++){
										$class = $model->setDateClass($workdata[$v][$i][0]);
										$datetime = new DateTime($workdata[$v][$i][0]);
										$w = (int)$datetime->format('w');

								?>
								<tr <?php if($workdata[$v][$i][0] == date('Y-m-d')){echo 'id="today"';}?>>

									<td class="<?= $class;?>"><?=$workdata[$v][$i][0]?></td>
									<td class="<?= $class;?>"><?=$week[$w]?></td>
									<td><?=$workdata[$v][$i][1]?></td>
									<td><?=$workdata[$v][$i][2]?></td>

									<?php if(empty($workdata[$v][$i][3])){?>

										<td></td><td></td>

									<?php
										}else{
											 for($j=0; $j<count($restdata); $j++){
											 	if($restdata[$j]['dayofweek'] == $w && $restdata[$j]['type'] == $workdata[$v][$i][4]){
									?>

														<td><?=$restdata[$j]['resttime']/3600?></td>

									<?php
														break;

											 	}
											}
									?>

										<td><?=($workdata[$v][$i][3]-$restdata[$j]['resttime'])/3600?></td>
									<?php }?>

										<td>
											<select name="status[]">
											<?php for($y=0; $y<count($statusinfo); $y++){?>
												<option value="<?=$statusinfo[$y][0]?>"
													<?php
													if($workdata[$v][$i][0] == $workstatus[$s][0]){
														if($workstatus[$s][1] == $statusinfo[$y][0]){echo ' selected';}
													}else{
														if($statusinfo[$y][0] == 3){echo ' selected';}}?>>
													<?=$statusinfo[$y][1]?>
												</option>
											<?php }?>
											</select>
										</td>

										<td>
											<textarea name="memo[]" rows="1" cols="15" id="memo"><?php
											if($workdata[$v][$i][0] == $workstatus[$s][0]){
												echo $workstatus[$s][3];
												if($s < count($workstatus)){
													$s++;
												}
											}?></textarea>
										</td>
										<input type="hidden" name="day[]" value="<?=$workdata[$v][$i][0]?>">
									<?php
										}
									?>
								</tr>
						</table>

						<table class="sum">
							<tr class="record">
								<th>勤務日数</th>
								<th><?=$sum[$v]['sumDay']?>
							</tr>
							<tr class="record">
								<th>合計勤務時間</th>
								<th><?=$sum[$v]['sumWorkTime']?></th>
							</tr>
						</table>
					<?php }?>

						<input type="hidden" name="accountid" value="<?=$model->getAccountId();?>">
						<div class="right"><input type="submit" name="execute" value="保存" id="record"></div>
						</form>
						<p class="right">
							<button class="exportExcel">excelに出力</button>　　
							<button class="exportPDF">PDFに出力</button>
						</p>
				</div>
			</div>
			<footer class="box footer">
				<p>Copyright © 2010-<?=date("Y")?> FusionOne Co.,Ltd. All Rights Reserved.</p>
			</footer>

		</div>
	</body>
</html>
