<?php
$workdata = $model->getWorkData();
$restdata = $model->getRestData();
$statusinfo = $model->getStatusInfo();
$workstatus = $model->getWorkStatus();
$sum = $model->getSum();
?>
<!DOCTYPE html>
<html lang="ja">
	<head>
		<meta charset="UTF-8">
		<link rel="stylesheet" href="../css/design.css">
		<link rel="stylesheet" href="../css/content.css">
		<script src="../jquery/jquery-1.11.3.min.js"></script>
		<script src="../script/workTime.js"></script>
		<script>
		function formChange(){
			radio = document.getElementsByName('work')
			if(radio[0].checked) {

				//フォーム
				document.getElementById('formYear').style.display = "";
				document.getElementById('formMonth').style.display = "none";
				document.getElementById('formPeriod').style.display = "none";

			}else if(radio[1].checked) {

				//フォーム
				document.getElementById('formYear').style.display = "none";
				document.getElementById('formMonth').style.display = "";
				document.getElementById('formPeriod').style.display = "none";

			}else if(radio[2].checked) {

				//フォーム
				document.getElementById('formYear').style.display = "none";
				document.getElementById('formMonth').style.display = "none";
				document.getElementById('formPeriod').style.display = "";

			}
		}

		//オンロードさせ、リロード時に選択を保持
		window.onload = formChange;

		</script>
		<title>勤務時間表(個人)画面</title>
	</head>
	<body>
		<div class="container">
			<header class="box">
				<h1 class="title">勤怠管理システム</h1>
			</header>

			<div class="box width70 clearfix">
				<div class="userInfo float-left">
					<p>
						ユーザー名 :  /
						権限 :
								管理者
					</p>
				</div>
			</div>

			<div class="box menu"><!-- ヘッダーメニュー-->
					<ul id="dropmenu">
		 				<li><a href="">メニュー</a>
		   			 		<ul>
		    				</ul>
		 				</li>
		  				<li><a href="../overallWorkTime/overallWorkTime.php">勤務時間表</a>
		   					<ul>
		   					</ul>
		 				</li>
		 				<li><a href="../settingHoliday/settingHoliday.php">休日設定</a>
		    				<ul>
		   					</ul>
		 				</li>
		  				<li><a href="#">ユーザー設定</a>
		   					<ul>
		     					<li><a href="../updateUser/updateUser.php">ユーザー設定変更</a></li>
		     					<li><a href="../insertUser/insertUser.php">ユーザー登録</a></li>
		   					</ul>
		  				</li>
		  				<li><a href="../settingRestTime/settingRestTime.php">休憩時間設定</a>
		   					<ul>
		   					</ul>
		  				</li>
					</ul>
			</div>

			<div class="box main-container">
				<div class="workTime">
					<p>条件検索</p>
					<div class="selectbox">
					<form action="personalWorkTime.php" method="POST">
						<table>
							<tr>
							<!--表示非表示の切り替え　年次-->

							<?php $yearList = createYearSet();?>
								<td id="formYear">
									<select name="year">
										<option value="<?=date("Y")?>"><?=date("Y")?></option>
										<?php for($a=0; $a<count($yearList); $a++){?>
										<option value="<?=$yearList[$a]?>"><?=$yearList[$a]?></option>
										<?php }?>
									</select> 年
								</td>

							<!--表示非表示の切り替え　月次-->
						       	<td id="formMonth">
									<input type="month" name="month">
								</td>

							<!--表示非表示の切り替え　期間-->
								<td id="formPeriod">
									 開始期間
									<input type="month" name="startDay">　
									終了期間
									<input type="month" name="endDay">
								</td>
							</tr>
						</table>
表示時間:<?php $work = $model->getWork();?>
            <label><input type="radio" name="work" value="year" onclick="formChange();"
            			<?php if($work == 'year'){echo 'checked';}?>>年次</label>
            <label><input type="radio" name="work" value="month" onclick="formChange();"
						<?php if($work == 'month'){echo ' checked';}?>>月次</label>
            <label><input type="radio" name="work" value="period" onclick="formChange();"
            			<?php if($work == 'period'){echo ' checked';}?>>期間</label>
						&nbsp;&nbsp;&nbsp;<input type="submit" name="execute" value="表示">
						<input type="hidden" name="accountid" value="<?=$model->getAccountId();?>">
						</form>
					</div>

					<br>
					<p>表示期間 : <?=$model->getInfomation();?></p>

					<form action="personalWorkTime.php" method="POST">
						<table class="worksheet">
							<caption><?=$model->getName();?>出勤表</caption>
								<tr class="record">
									<td>日付</td>
									<td>曜日</td>
									<td>出勤</td>
									<td>退勤</td>
									<td>休憩時間</td>
									<td>実働時間</td>
									<td>ステータス</td>
									<td>備考欄</td>
								</tr>

								<?php
									$s=0;
									for($i=0;$i<count($workdata); $i++){
									$datetime = new DateTime($workdata[$i][0]);
									$week = array('日','月','火','水','木','金','土');
									$w = (int)$datetime->format('w');
								?>
								<tr>
									<td><?=$workdata[$i][0]?></td>
									<td><?=$week[$w]?></td>
									<td><?=$workdata[$i][1]?></td>
									<td><?=$workdata[$i][2]?></td>

									<?php if(empty($workdata[$i][3])){?>

										<td></td><td></td>

									<?php
										}else{
											 for($j=0; $j<count($restdata); $j++){
											 	if($restdata[$j]['dayofweek'] == $w){
													if($restdata[$j]['type'] == $workdata[$i][4]){
									?>

														<td><?=$restdata[$j]['resttime']/3600?></td>

									<?php
														break;
													}
											 	}
											}
									?>

										<td><?=($workdata[$i][3]-$restdata[$j]['resttime'])/3600?></td>
									<?php }?>

										<td>
											<select name="status[]">
											<?php for($y=0; $y<count($statusinfo); $y++){?>
												<option value="<?=$statusinfo[$y][0]?>"
													<?php
													if(isset($workstatus[$s])){
														if($workstatus[$s][1] == $statusinfo[$y][0]){echo ' selected';}}?>>
													<?=$statusinfo[$y][1]?>
												</option>
											<?php }?>
											</select>
										</td>

										<td>
											<textarea name="memo[]" rows="1" cols="15"><?php
											if(isset($workstatus[$s])){
												if($workdata[$i][0] == $workstatus[$s][0]){
													echo $workstatus[$s][3];
													$s++;
												}
											}?></textarea>
										</td>
										<input type="hidden" name="day[]" value="<?=$workdata[$i][0]?>">
									<?php
										}
									?>
								</tr>
						</table>

						<table class="sum">
							<tr class="record">
								<th>勤務日数</th>
								<th><?=$sum['sumDay']?>
							</tr>
							<tr class="record">
								<th>合計勤務時間</th>
								<th><?=$sum['sumWorkTime']?></th>
							</tr>
						</table>

						<input type="hidden" name="accountid" value="<?=$model->getAccountId();?>">
						<div class="right"><input type="submit" name="execute" value="保存" id="record"></div>
						</form>
						<p class="right">
							<button class="exportExcel">excelに出力</button>　　
							<button class="exportPDF">PDFに出力</button>
						</p>
				</div>
			</div>

			<footer class="box footer">
				<p>Copyright © 2010-2015 FusionOne Co.,Ltd. All Rights Reserved.</p>
			</footer>

		</div>
	</body>
</html>
