<?php
$holiday = $model->getHolidayData();
?>
<!DOCTYPE html>
<html lang="ja">
	<head>
		<meta charset="UTF-8">
		<link rel="stylesheet" href="../css/design.css">
		<link rel="stylesheet" href="../css/content.css">
		<script src="../jquery/jquery-1.11.3.min.js"></script>
		<script src="../jquery/jquery-ui.js"></script>
		<title>休日設定画面</title>
	</head>
	<body>
		<div class="container">
			<header class="box">
				<h1 class="title">勤怠管理システム</h1>
			</header>

			<div class="box width70 clearfix">
				<div class="userInfo float-left">
					<p>ユーザー名 : admin / 権限 : 管理者</p>
				</div>
				<div class="userInfo float-right">
					<p><a href="login.html">ログアウト</a></p>
				</div>
			</div>

			<div class="box menu"><!-- ヘッダーメニュー-->
				<ul id="dropmenu">
	 				<li><a href="../mainMenu/mainMenu.php">メニュー</a>
	   			 		<ul>
	    				</ul>
	 				 </li>
	  				<li><a href="../overallWorkTime/overallWorkTime.php">勤務時間表</a>
	   					<ul>
	   					</ul>
	 				</li>
	 				<li><a href="settingHoliday.php">休日設定</a>
	    				<ul>
	   					</ul>
	 				</li>
	  				<li><a href="#">ユーザー設定</a>
	   					<ul>
	     					<li><a href="../updateUser/updateUser.php">ユーザー設定変更</a></li>
	     					<li><a href="../insertUser/insertUser.php">ユーザー登録</a></li>
	   					</ul>
	  				</li>
	  				<li><a href="../settingRestTime/settingRestTime.php">休憩時間設定</a>
	   					<ul>
	   					</ul>
	  				</li>
				</ul>
			</div>

			<div class="box main-container">
			<div class="holidaydd">
				<dl>
					<dt>休日個別登録</dt>
						<dd>
							<p>
								<form action="settingHoliday.php" method="POST">
									日付選択 ： <input type="date" name="holiday">
									種別  : <select name="type">
											<option value="1">公休</option>
											<option value="2">祝日</option>
										  </select>
									<input type="submit" value="登録">
									<input type="hidden" name="execute" value="single">
								</form>
							</p>
						</dd>

					<dt>休日一括登録</dt>
						<dd>
								<div id="holidaybox">
									<div class="holidayForm">
										<h3>曜日一括登録</h3>
										<form action="settingHoliday.php" method="POST">
										土 <input type="checkbox" name="dayOfWeek[]" value="6" >
										日 <input type="checkbox" name="dayOfWeek[]" value="0">

										&nbsp;&nbsp;

										開始日付 ： <input type="date" name="startHoliday">
										終了日付 ： <input type="date" name="endHoliday">
										種別 :    <select name="type">
													<option value="1">公休</option>
													<option value="2">祝日</option>
												 </select>

										<input type="submit" value="登録">
										<input type="hidden" name="execute" value="StuSun">
									</form>

									</div>
									<div class="holidayForm">
										<h3>CSV一括登録</h3>
										<form action="settingHoliday.php" method="POST">
										年（yyyy）,月(mm),日(dd),種別,の形式でカンマ区切りで入力して下さい。<br><br>
										例) 2015,8,15,公休,<br>
										<center>
											<textarea rows="10" cols="80" name=textarea></textarea>
											<br>
											<br>

											<input type="submit" value="登録">
											<input type="reset" value="リセット">
											<input type="hidden" name="execute" value="bulk">
										</center>
										</form>
									</div>
								</div>

						</dd>

				</dl>
				</div>
				<div id="holidayListTitle">

					休日一覧

				</div>
				<?php $page = $model->getPage();?>
				<div class="holidaylist">
					<center>
					<?php if(!$page <= 0){?>
					<a href="settingHoliday.php?page=<?=$page-1?>">＜＜ 前の20件を表示</a>
					<?php }?>
					&nbsp;&nbsp;
					<a href="settingHoliday.php?page=<?=$page+1?>">次の20件を表示 ＞＞</a>
					<table border="2">
						<tr class="record"><td>年/月/日</td><td>曜日</td><td>種別</td><td>変更/削除</td></tr>
						<?php
						for($i=$page*20; $i<$page*20 + 20; $i++){
							if(!isset($holiday[$i]['day'])){
								break;
							}else{
								$datetime = new DateTime($holiday[$i]['day']);
								$week = array('日','月','火','水','木','金','土');
								$w = (int)$datetime->format('w');
						?>
						<tr>
							<td><?=$holiday[$i]['day']?></td><td><?=$week[$w]?></td><td><?=$holiday[$i]['name']?></td>
							<td>
								<a href="javascript:void(0)" class="update" data-dubug="1">変更</a>&nbsp;&nbsp;
								<a href="settingHoliday.php?deleteid=<?=$holiday[$i]['holidayid']?>" class="delete">削除</a>
							</td>
						</tr>
						<?php
							}
						}?>
					</table>
					</center>
				</div>

			</div>
			<footer class="box footer">
				<p>Copyright © 2010-2015 FusionOne Co.,Ltd. All Rights Reserved.</p>
			</footer>

		</div>
<div id="jquery-ui-dialog2" title="出勤情報修正">
    <form>
    <fieldset>
        <p class="changename"></p>
        <p>
            <label for="jquery-ui-dialog-form-hour2">出勤時間</label>
            <select name="jquery-ui-dialog-form-hour2" id="jquery-ui-dialog-form-hour2" class="text ui-widget-content ui-corner-all" />
            	<?php for($hour3=1; $hour3 <= 24 ;$hour3++){?>
	            	<option value="<?php echo $hour3;?>"><?php echo $hour3;?></option>
	            <?php }?>
            </select>
   			時
   			<select name="jquery-ui-dialog-form-minute2" id="jquery-ui-dialog-form-minute2" class="text ui-widget-content ui-corner-all" />
            	<option value="00">00</option>
            	<option value="10">10</option>
               	<option value="20">20</option>
				<option value="30">30</option>
				<option value="40">40</option>
				<option value="50">50</option>
            </select>
			 分
        </p>

        <p>
            <label for="jquery-ui-dialog-form-endhour2">退勤時間</label>
            <select name="jquery-ui-dialog-form-endhour2" id="jquery-ui-dialog-form-endhour2" class="text ui-widget-content ui-corner-all" />
            	<?php for($hour4=1; $hour4 <= 24 ;$hour4++){?>
	            	<option value="<?php echo $hour4;?>"><?php echo $hour4;?></option>
	            <?php }?>
            </select>
   			時
   			<select name="jquery-ui-dialog-form-endminute2" id="jquery-ui-dialog-form-endminute2" class="text ui-widget-content ui-corner-all" />
            	<option value="00">00</option>
				<option value="10">10</option>
				<option value="20">20</option>
				<option value="30">30</option>
				<option value="40">40</option>
				<option value="50">50</option>
            </select>
			 分
        </p>

    </fieldset>
    	<input type="hidden" name="accountid" id=accountid>
    	 <input type="hidden" name="year2" id="year2">
        <input type="hidden" name="month2" id="month2">
        <input type="hidden" name="day2" id="day2">
    </form>
</div>
		<script>
		$(function(){

			$('a[href="login.html"]').click(function() {
				if (!confirm('ログアウトします。\nよろしいですか？')) {
					return false;
				}
			});


			$('#setSingle').click(function() {
				if (!confirm('設定した休日で登録します。\nよろしいですか？')) {
					return false;
				}
			});

			$('#setStuSun').click(function() {
				if (!confirm('曜日一括登録します。\nよろしいですか？')) {
					return false;
				}
			});

			$('#setBulk').click(function() {
				if (!confirm('記述した日程で一括登録します。\nよろしいですか？')) {
					return false;
				}
			});

			$('.delete').click(function() {
				if (!confirm('選択した休日を削除します。\nよろしいですか？')) {
					return false;
				}
			});

			$("dd:not(:first)").css("display","none");

			$("dl dt").click(function(){
				if($("+dd",this).css("display")=="none"){
			        $("dd").slideUp();
			        $("+dd",this).slideDown();
			    }
			});
		});

		jQuery( function() {
		    jQuery( 'a.update' ) . click( function() {
				console.log($(this).data('dubug'));
		        jQuery( '#jquery-ui-dialog2' ) . dialog( 'open' );
		    } );

		    jQuery( '#jquery-ui-dialog2' ) . dialog( {
		        autoOpen: false,
		        width: 350,
		        show: 'explode',
		        hide: 'explode',
		        modal: true,
		        buttons: {
	            '変更': function() {
		    	 if (hour2 . val() ) {
	                	$.ajax({
		  				      type: 'POST',
		  				      url:'mainMenu.php',
		  				      data:{
	                			"accountid": $(':hidden[name="accountid"]').val(),
		  						"formYear": $(':hidden[name="year2"]').val(),
		  						"formMonth": $(':hidden[name="month2"]').val(),
		  						"formDay": $(':hidden[name="day2"]').val(),
		  						"workstarthour": $('#jquery-ui-dialog-form-hour2 option:selected').val(),
			  					"workstartminute": $('#jquery-ui-dialog-form-minute2 option:selected').val(),
				  				"workendhour": $('#jquery-ui-dialog-form-endhour2 option:selected').val(),
					  			"workendminute": $('#jquery-ui-dialog-form-endminute2 option:selected').val(),
					  			"execute": "update"

		  				      },
		  				      success:function(data) {

			  				    location.reload();

		  				      },
		  				      error:function(XMLHttpRequest, textStatus, errorThrown) {

		  				   	 　}
		  				 });

	                    jQuery( this ).dialog( 'close' );
	                }
	                jQuery( this ) . dialog( 'close' );
	            },
	            '削除': function() {
	            	$.ajax({
	  				      type: 'POST',
	  				      url:'mainMenu.php',
	  				      data:{
	            			"accountid": $(':hidden[name="accountid"]').val(),
	            			"formYear": $(':hidden[name="year2"]').val(),
	  						"formMonth": $(':hidden[name="month2"]').val(),
	  						"formDay": $(':hidden[name="day2"]').val(),
				  			"execute": "delete"

	  				      },
	  				      success:function(data) {

		  				    location.reload();

	  				      },
	  				      error:function(XMLHttpRequest, textStatus, errorThrown) {

	  				   	 　}
	  				 });
	                jQuery( this ) . dialog( 'close' );
	            },
	            'キャンセル': function() {
	                jQuery( this ) . dialog( 'close' );
	            },
	        }
	    } );
	} );

		</script>
	</body>
</html>