<?php
$holiday = $model->getHolidayData();
?>
<!DOCTYPE html>
<html lang="ja">
	<head>
		<meta charset="UTF-8">
		<link rel="stylesheet" href="../css/design.css">
		<link rel="stylesheet" href="../css/content.css">
		<link rel="stylesheet" href="../jquery/jquery-ui.css">
		<script src="../jquery/jquery-1.11.3.min.js"></script>
		<script src="../jquery/jquery-ui.js"></script>
		<script src="../script/logout.js"></script>
		<script src="../script/settingHoliday.js"></script>
		<title>休日設定画面</title>
	</head>
	<body>
		<div class="container">
			<header class="box">
				<h1 class="title">勤怠管理システム</h1>
			</header>

			<div class="box width70 clearfix">
				<div class="userInfo float-left">
					<p>
						ユーザー名 : <?php echo $_SESSION['userinfo']['name'];?> /
						権限 : <?php if($_SESSION['userinfo']['authority'] == 2){?>
								管理者
							  <?php }else{?>
							  	一般ユーザー
							  <?php }?>
					</p>
				</div>
				<div class="userInfo float-right">
					<p><a href="../login/login.php?execute=logout" id="logoutLink">ログアウト</a></p>
				</div>
			</div>

			<div class="box menu"><!-- ヘッダーメニュー-->
				<ul id="dropmenu">
	 				<li><a href="../mainMenu/mainMenu.php">メニュー</a>
	   			 		<ul>
	    				</ul>
	 				</li>
	  				<li><a href="../overallWorkTime/overallWorkTime.php">勤務時間表</a>
	   					<ul>
	   					</ul>
	 				</li>
	 				<li><a href="settingHoliday.php">休日設定</a>
	    				<ul>
	   					</ul>
	 				</li>
	  				<li><a href="#">管理設定</a>
	   					<ul>
	     					<li><a href="../updateUser/updateUser.php">ユーザー設定変更</a></li>
	     					<li><a href="../insertUser/insertUser.php">ユーザー登録</a></li>
	     					<li><a href="../eventList/eventList.php">セミナー一覧</a></li>
	     					<li><a href="../insertEvent/insertEvent.php">セミナー登録</a></li>
	   					</ul>
	  				</li>
	  				<li><a href="../settingRestTime/settingRestTime.php">休憩時間設定</a>
	   					<ul>
	   					</ul>
	  				</li>
				</ul>
			</div>

			<div class="box main-container">
				<div class="holidaydd">
					<dl>
						<dt>休日個別登録</dt>
							<dd>
								<p>
									<form action="settingHoliday.php" method="POST">
										日付選択 ： <input type="date" name="holiday" value="<?=date('Y-m-d')?>">　
										種別  : <select name="type">
										<!-- 後日DBから取得して表示するように修正 -->
												<option value="1">公休</option>
												<option value="2">祝日</option>
											  </select>　
										祝日名 : <input type="text" name="holidayName" value="">
										<input type="submit" value="登録" id="setSingle">
										<input type="hidden" name="execute" value="single">
									</form>
								</p>
							</dd>

						<dt>休日一括登録</dt>
							<dd>
								<div id="holidaybox">

									<div class="holidayForm">

										<h3>曜日一括登録</h3>
										<form action="settingHoliday.php" method="POST">
											<table>
												<tr>
													<td>
														土 <input type="checkbox" name="dayOfWeek[]" id="saturday" value="6" >
														日 <input type="checkbox" name="dayOfWeek[]" id="sunday" value="0">
														  <input type="hidden" name="dayOfWeek[]" value="" >
													</td>
												</tr>
												<tr>
													<td>
														開始日付 ： <input type="date" name="startHoliday" value="<?=date('Y-m-01')?>">
														終了日付 ： <input type="date" name="endHoliday" value="<?=date('Y-m-t')?>">
														種別 :    <select name="type">
																	<option value="1">公休</option>
																	<option value="2">祝日</option>
																 </select>
													</td>
												</tr>
												<tr>
													<td height="30px">
													</td>
												</tr>
												<tr>
													<td align="center">
														<input type="submit" value="登録" id="setStuSun">
														<input type="hidden" name="execute" value="StuSun">
													</td>
												</tr>
											</table>
										</form>
									</div>

									<div class="holidayForm">
										<h3>CSV一括登録</h3>
										<form action="settingHoliday.php" method="POST">
											{年（yyyy）,月(mm),日(dd),種別,休日名}の形式でカンマ区切りで入力して下さい。<br><br>
											例) 2015,8,15,公休,メンテナンス日<br>
												&nbsp;&nbsp;&nbsp;&nbsp;
												2015,9,23,祝日,秋分の日<br>
											<center>
												<textarea rows="10" cols="80" name=textarea id="textarea"></textarea>
												<br>
												<br>

												<input type="submit" value="登録" id="setBulk">
												<input type="reset" value="リセット">
												<input type="hidden" name="execute" value="bulk">
											</center>
										</form>
									</div>
								</div>

							</dd>

					</dl>
				</div>

				<div id="holidayListTitle">

					休日一覧

				</div>

				<?php $page = $model->getPage();?>
				<div class="holidaylist">
					<center>
						<?php if(!$page <= 0){?>
						<a href="settingHoliday.php?page=<?=$page-1?>">＜＜ 前の20件を表示</a>
						<?php }?>
						&nbsp;&nbsp;
						<?php if(count($holiday)-($page*20+20) >= 0){?>
						<a href="settingHoliday.php?page=<?=$page+1?>">次の20件を表示 ＞＞</a>
						<?php }?>
						<table border="2">
							<tr class="record">
								<td>年/月/日</td>
								<td>曜日</td>
								<td>種別</td>
								<td>名前</td>
								<td>変更/削除</td>
							</tr>
							<?php
							for($i=$page*20; $i<$page*20 + 20; $i++){
								if(!isset($holiday[$i]['day'])){
									break;
								}else{
									$datetime = new DateTime($holiday[$i]['day']);
									$week = array('日','月','火','水','木','金','土');
									$w = (int)$datetime->format('w');
							?>
							<tr>
								<td><?=$holiday[$i]['day']?></td>
								<td><?=$week[$w]?></td>
								<td><?=$holiday[$i]['name']?></td>
								<td><?=$holiday[$i]['holidayName']?></td>
								<td>
									<a href="javascript:void(0)" class="update"
									   data-id="<?=$holiday[$i]['holidayid']?>"
									   data-day="<?=$holiday[$i]['day']?>"
									   data-type="<?=$holiday[$i]['typeid']?>"
									   data-name="<?=$holiday[$i]['holidayName']?>">
										 変更
									</a>&nbsp;&nbsp;
									<a href="settingHoliday.php?execute=delete&holidayid=<?=$holiday[$i]['holidayid']?>"
										class="delete">削除</a>
								</td>
							</tr>
							<?php
								}
							}?>
						</table>
					</center>
				</div>

			</div>
			<footer class="box footer">
				<p>Copyright © 2010-<?=date("Y")?> FusionOne Co.,Ltd. All Rights Reserved.</p>
			</footer>

		</div>
		<div id="update-dialog" title="休日設定変更">
		    <form>
		    <fieldset>
		        <p>
		        	日付
		            <input type="date" name="dialog-holiday" id="dialog-holiday">
		        </p>

		        <p>
		          	  種別
		            <select name="dialog-type" id="dialog-type" />
		            	<option value="1">公休</option>
		            	<option value="2">祝日</option>
		            </select>
		        </p>

		        <p>
		        	名前
		        	<input type="text" name="dialog-name" id="dialog-name" />
		        </p>

		    </fieldset>

		    	<input type="hidden" name="oldDay" id="oldDay">
		    	<input type="hidden" name="holidayid" id="holidayid">
		    </form>
		</div>

	</body>
</html>