<?php
$data = $model->getRestTimeData();
?>
<!DOCTYPE html>
<html lang="ja">
	<head>
		<meta charset="UTF-8">
		<link rel="stylesheet" href="../css/design.css">
		<link rel="stylesheet" href="../css/content.css">
		<script src="../jquery/jquery-1.11.3.min.js"></script>
		<script src="../script/logout.js"></script>
		<script>

		$(function(){

			$('#setRestTime').click(function() {
				if (!confirm('設定した休憩時間で登録します。\nよろしいですか？')) {
					return false;
				}
			});


			<?php
			$g=0;
			$s=0;
			for($i=0; $i<count($data); $i++){
				list($startHour, $startMinuts) = explode(":", $data[$i]['reststarttime']);
				list($endHour, $endMinuts) = explode(":", $data[$i]['restendtime']);
				if($data[$i]['type'] == 1){
			?>
					$("select#startHour<?=$g?>").val(<?= $startHour?>);
					$("select#startMinuts<?=$g?>").val("<?= $startMinuts?>");
					$("select#endHour<?=$g?>").val(<?= $endHour?>);
					$("select#endMinuts<?=$g?>").val("<?= $endMinuts?>");
			<?php
					++$g;
				}else{?>
					$("select#seminarStartHour<?=$s?>").val(<?= $startHour?>);
					$("select#seminarStartMinuts<?=$s?>").val("<?= $startMinuts?>");
					$("select#seminarEndHour<?=$s?>").val(<?= $endHour?>);
					$("select#seminarEndMinuts<?=$s?>").val("<?= $endMinuts?>");
				<?php
					++$s;
				}
			 }?>
		});

		</script>
		<title>休憩時間設定画面</title>
	</head>
	<body>
		<div class="container">
			<header class="box">
				<h1 class="title">勤怠管理システム</h1>
			</header>

			<div class="box width70 clearfix">
				<div class="userInfo float-left">
					<p>
						ユーザー名 : <?php echo $_SESSION['userinfo']['name'];?> /
						権限 : <?php if($_SESSION['userinfo']['authority'] == 2){?>
								管理者
							  <?php }else{?>
							  	一般ユーザー
							  <?php }?>
					</p>
				</div>
				<div class="userInfo float-right">
					<p><a href="../login/login.php?execute=logout" id="logoutLink">ログアウト</a></p>
				</div>
			</div>

			<div class="box menu"><!-- ヘッダーメニュー-->
				<ul id="dropmenu">
	 				<li><a href="../mainMenu/mainMenu.php">メニュー</a>
	   			 		<ul></ul>
	 				</li>
	  				<li><a href="../overallWorkTime/overallWorkTime.php">勤務時間表</a>
	   					<ul></ul>
	 				</li>
	 				<li><a href="../settingHoliday/settingHoliday.php">休日設定</a>
	    				<ul></ul>
	 				</li>
	  				<li><a href="#">管理設定</a>
	   					<ul>
	     					<li><a href="../updateUser/updateUser.php">ユーザー設定変更</a></li>
	     					<li><a href="../insertUser/insertUser.php">ユーザー登録</a></li>
	     					<li><a href="../eventList/eventList.php">セミナー一覧</a></li>
	     					<li><a href="../insertEvent/insertEvent.php">セミナー登録</a></li>
	   						<li><a href="../managementElements/managementElements.php">各種設定一覧</a></li>
	   					</ul>
	  				</li>
	  				<li><a href="settingRestTime.php">休憩時間設定</a>
	   					<ul></ul>
	  				</li>
				</ul>
			</div>

			<div class="box main-container">

				<div class="restbox clearfix" >
					<div id="title">休憩時間設定</div>
						<div class="float-left" id="dayofWeekTitle">
							曜日
						</div>
						<div class="setRestTimeTitle">
							休憩開始時間
						</div>
						<div class="setRestTimeTitle">
							休憩終了時間
						</div>
				</div>

				<form action="settingRestTime.php" method="POST">
				<div class="restbox clearfix">

					<div class="dayOfWeekbox float-left weekboxHeight" style="width: 20%">
						日曜日
					</div>
					<div class="setRestTimebox float-left" style="width: 40%; font-size: 14px;">

						<p class="startColor">一般&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; :
							<select name="startHour[]" id="startHour0">
							<?php for($i=1; $i<=24; $i++){?>
								<option value="<?=$i?>"><?=$i?></option>
							<?php }?>
							</select>

							 時
							<select name="startMinuts[]" id="startMinuts0">
									<option value="00">00</option>
									<option value="10">10</option>
									<option value="20">20</option>
									<option value="30">30</option>
									<option value="40">40</option>
									<option value="50">50</option>
							 </select>
							 分</p>
						<p>セミナー :
							<select name="seminarStartHour[]" id="seminarStartHour0">
								<?php for($i=1; $i<=24; $i++){?>
								<option value="<?=$i?>"><?=$i?></option>
								<?php }?>
							 </select>

							 時
							<select name="seminarStartMinuts[]" id="seminarStartMinuts0">
									<option value="00">00</option>
									<option value="10">10</option>
									<option value="20">20</option>
									<option value="30">30</option>
									<option value="40">40</option>
									<option value="50">50</option>
							 </select>
							 分</p>

					</div>
					<div class="setRestTimebox float-left" style="width: 40%; font-size:14px;">
						<p class="startColor">一般&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; :
							<select name="endHour[]" id="endHour0">
								<?php for($i=1; $i<=24; $i++){?>
								<option value="<?=$i?>"><?=$i?></option>
								<?php }?>
							 </select>

							 時
							<select name="endMinuts[]" id="endMinuts0">
									<option value="00">00</option>
									<option value="10">10</option>
									<option value="20">20</option>
									<option value="30">30</option>
									<option value="40">40</option>
									<option value="50">50</option>
							 </select>
							 分</p>
						<p>セミナー :
							<select name="seminarEndHour[]"  id="seminarEndHour0">
								<?php for($i=1; $i<=24; $i++){?>
								<option value="<?=$i?>"><?=$i?></option>
								<?php }?>
							 </select>

							 時
							<select name="seminarEndMinuts[]" id="seminarEndMinuts0">
									<option value="00">00</option>
									<option value="10">10</option>
									<option value="20">20</option>
									<option value="30">30</option>
									<option value="40">40</option>
									<option value="50">50</option>
							 </select>
							 分</p>

					</div>
					<input type="hidden" name="dayofweek[]" value="0">
				</div>
				<div class="restbox clearfix">

					<div class="dayOfWeekbox float-left weekboxHeight" style="width: 20%">
						月曜日
					</div>
					<div class="setRestTimebox float-left" style="width: 40%; font-size:14px;">

						<p class="startColor">一般&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; :
							<select name="startHour[]" id="startHour1">
								<?php for($i=1; $i<=24; $i++){?>
								<option value="<?=$i?>"><?=$i?></option>
								<?php }?>
							 </select>

							 時
							<select name="startMinuts[]" id="startMinuts1">
									<option value="00">00</option>
									<option value="10">10</option>
									<option value="20">20</option>
									<option value="30">30</option>
									<option value="40">40</option>
									<option value="50">50</option>
							 </select>
							 分</p>
						<p>セミナー :
							<select name="seminarStartHour[]" id="seminarStartHour1">
								<?php for($i=1; $i<=24; $i++){?>
								<option value="<?=$i?>"><?=$i?></option>
								<?php }?>
							 </select>

							 時
							<select name="seminarStartMinuts[]" id="seminarStartMinuts1">
									<option value="00">00</option>
									<option value="10">10</option>
									<option value="20">20</option>
									<option value="30">30</option>
									<option value="40">40</option>
									<option value="50">50</option>
							 </select>
							 分</p>

					</div>
					<div class="setRestTimebox float-left" style="width: 40%; font-size:14px;">
						<p class="startColor">一般&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; :
							<select name="endHour[]" id="endHour1">
								<?php for($i=1; $i<=24; $i++){?>
								<option value="<?=$i?>"><?=$i?></option>
								<?php }?>
							 </select>

							 時
							<select name="endMinuts[]" id="endMinuts1">
									<option value="00">00</option>
									<option value="10">10</option>
									<option value="20">20</option>
									<option value="30">30</option>
									<option value="40">40</option>
									<option value="50">50</option>
							 </select>
							 分</p>
						<p>セミナー :
							<select name="seminarEndHour[]" id="seminarEndHour1">
								<?php for($i=1; $i<=24; $i++){?>
								<option value="<?=$i?>"><?=$i?></option>
								<?php }?>
							 </select>

							 時
							<select name="seminarEndMinuts[]" id="seminarEndMinuts1">
									<option value="00">00</option>
									<option value="10">10</option>
									<option value="20">20</option>
									<option value="30">30</option>
									<option value="40">40</option>
									<option value="50">50</option>
							 </select>
							 分</p>

					</div>
					<input type="hidden" name="dayofweek[]" value="1">
				</div>
				<div class="restbox clearfix">

					<div class="dayOfWeekbox float-left weekboxHeight" style="width: 20%">
						火曜日
					</div>
					<div class="setRestTimebox float-left" style="width: 40%; font-size: 14px;">

						<p class="startColor">一般&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; :
							<select name="startHour[]" id="startHour2">
								<?php for($i=1; $i<=24; $i++){?>
								<option value="<?=$i?>"><?=$i?></option>
								<?php }?>
							 </select>

							 時
							<select name="startMinuts[]" id="startMinuts2">
									<option value="00">00</option>
									<option value="10">10</option>
									<option value="20">20</option>
									<option value="30">30</option>
									<option value="40">40</option>
									<option value="50">50</option>
							 </select>
							 分</p>
						<p>セミナー :
							<select name="seminarStartHour[]" id="seminarStartHour2">
								<?php for($i=1; $i<=24; $i++){?>
								<option value="<?=$i?>"><?=$i?></option>
								<?php }?>
							 </select>

							 時
							<select name="seminarStartMinuts[]" id="seminarStartMinuts2">
									<option value="00">00</option>
									<option value="10">10</option>
									<option value="20">20</option>
									<option value="30">30</option>
									<option value="40">40</option>
									<option value="50">50</option>
							 </select>
							 分</p>

					</div>
					<div class="setRestTimebox float-left" style="width: 40%; font-size:14px;">
						<p class="startColor">一般&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; :
							<select name="endHour[]" id="endHour2">
								<?php for($i=1; $i<=24; $i++){?>
								<option value="<?=$i?>"><?=$i?></option>
								<?php }?>
							 </select>

							 時
							<select name="endMinuts[]" id="endMinuts2">
									<option value="00">00</option>
									<option value="10">10</option>
									<option value="20">20</option>
									<option value="30">30</option>
									<option value="40">40</option>
									<option value="50">50</option>
							 </select>
							 分</p>
						<p>セミナー :
							<select name="seminarEndHour[]" id="seminarEndHour2">
								<?php for($i=1; $i<=24; $i++){?>
								<option value="<?=$i?>"><?=$i?></option>
								<?php }?>
							 </select>

							 時
							<select name="seminarEndMinuts[]" id="seminarEndMinuts2">
									<option value="00">00</option>
									<option value="10">10</option>
									<option value="20">20</option>
									<option value="30">30</option>
									<option value="40">40</option>
									<option value="50">50</option>
							 </select>
							 分</p>
					<input type="hidden" name="dayofweek[]" value="2">
					</div>

				</div>
				<div class="restbox clearfix">

					<div class="dayOfWeekbox float-left weekboxHeight" style="width: 20%">
						水曜日
					</div>
					<div class="setRestTimebox float-left" style="width: 40%; font-size: 14px;">

						<p class="startColor">一般&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; :
							<select name="startHour[]" id="startHour3">
								<?php for($i=1; $i<=24; $i++){?>
								<option value="<?=$i?>"><?=$i?></option>
								<?php }?>
							 </select>

							 時
							<select name="startMinuts[]" id="startMinuts3">
									<option value="00">00</option>
									<option value="10">10</option>
									<option value="20">20</option>
									<option value="30">30</option>
									<option value="40">40</option>
									<option value="50">50</option>
							 </select>
							 分</p>
						<p>セミナー :
							<select name="seminarStartHour[]" id="seminarStartHour3">
								<?php for($i=1; $i<=24; $i++){?>
								<option value="<?=$i?>"><?=$i?></option>
								<?php }?>
							 </select>

							 時
							<select name="seminarStartMinuts[]" id="seminarStartMinuts3">
									<option value="00">00</option>
									<option value="10">10</option>
									<option value="20">20</option>
									<option value="30">30</option>
									<option value="40">40</option>
									<option value="50">50</option>
							 </select>
							 分</p>

					</div>
					<div class="setRestTimebox float-left" style="width: 40%; font-size:14px;">
						<p class="startColor">一般&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; :
							<select name="endHour[]" id="endHour3">
								<?php for($i=1; $i<=24; $i++){?>
								<option value="<?=$i?>"><?=$i?></option>
								<?php }?>
							 </select>

							 時
							<select name="endMinuts[]" id="endMinuts3">
									<option value="00">00</option>
									<option value="10">10</option>
									<option value="20">20</option>
									<option value="30">30</option>
									<option value="40">40</option>
									<option value="50">50</option>
							 </select>
							 分</p>
						<p>セミナー :
							<select name="seminarEndHour[]" id="seminarEndHour3">
								<?php for($i=1; $i<=24; $i++){?>
								<option value="<?=$i?>"><?=$i?></option>
								<?php }?>
							 </select>

							 時
							<select name="seminarEndMinuts[]" id="seminarEndMinuts3">
									<option value="00">00</option>
									<option value="10">10</option>
									<option value="20">20</option>
									<option value="30">30</option>
									<option value="40">40</option>
									<option value="50">50</option>
							 </select>
							 分</p>
					<input type="hidden" name="dayofweek[]" value="3">
					</div>

				</div>
				<div class="restbox clearfix">

					<div class="dayOfWeekbox float-left weekboxHeight" style="width: 20%">
						木曜日
					</div>
					<div class="setRestTimebox float-left" style="width: 40%; font-size: 14px;">

						<p class="startColor">一般&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; :
							<select name="startHour[]" id="startHour4">
								<?php for($i=1; $i<=24; $i++){?>
								<option value="<?=$i?>"><?=$i?></option>
								<?php }?>
							 </select>

							 時
							<select name="startMinuts[]" id="startMinuts4">
									<option value="00">00</option>
									<option value="10">10</option>
									<option value="20">20</option>
									<option value="30">30</option>
									<option value="40">40</option>
									<option value="50">50</option>
							 </select>
							 分</p>
						<p>セミナー :
							<select name="seminarStartHour[]" id="seminarStartHour4">
								<?php for($i=1; $i<=24; $i++){?>
								<option value="<?=$i?>"><?=$i?></option>
								<?php }?>
							 </select>

							 時
							<select name="seminarStartMinuts[]" id="seminarStartMinuts4">
									<option value="00">00</option>
									<option value="10">10</option>
									<option value="20">20</option>
									<option value="30">30</option>
									<option value="40">40</option>
									<option value="50">50</option>
							 </select>
							 分</p>

					</div>
					<div class="setRestTimebox float-left" style="width: 40%; font-size:14px;">
						<p class="startColor">一般&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; :
							<select name="endHour[]" id="endHour4">
								<?php for($i=1; $i<=24; $i++){?>
								<option value="<?=$i?>"><?=$i?></option>
								<?php }?>
							 </select>

							 時
							<select name="endMinuts[]" id="endMinuts4">
									<option value="00">00</option>
									<option value="10">10</option>
									<option value="20">20</option>
									<option value="30">30</option>
									<option value="40">40</option>
									<option value="50">50</option>
							 </select>
							 分</p>
						<p>セミナー :
							<select name="seminarEndHour[]" id="seminarEndHour4">
								<?php for($i=1; $i<=24; $i++){?>
								<option value="<?=$i?>"><?=$i?></option>
								<?php }?>
							 </select>

							 時
							<select name="seminarEndMinuts[]" id="seminarEndMinuts4">
									<option value="00">00</option>
									<option value="10">10</option>
									<option value="20">20</option>
									<option value="30">30</option>
									<option value="40">40</option>
									<option value="50">50</option>
							 </select>
							 分</p>
					<input type="hidden" name="dayofweek[]" value="4">
					</div>

				</div>
				<div class="restbox clearfix">

					<div class="dayOfWeekbox float-left weekboxHeight" style="width: 20%">
						金曜日
					</div>
					<div class="setRestTimebox float-left" style="width: 40%; font-size: 14px;">

						<p class="startColor">一般&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; :
							<select name="startHour[]" id="startHour5">
								<?php for($i=1; $i<=24; $i++){?>
								<option value="<?=$i?>"><?=$i?></option>
								<?php }?>
							 </select>

							 時
							<select name="startMinuts[]" id="startMinuts5">
									<option value="00">00</option>
									<option value="10">10</option>
									<option value="20">20</option>
									<option value="30">30</option>
									<option value="40">40</option>
									<option value="50">50</option>
							 </select>
							 分</p>
						<p>セミナー :
							<select name="seminarStartHour[]" id="seminarStartHour5">
								<?php for($i=1; $i<=24; $i++){?>
								<option value="<?=$i?>"><?=$i?></option>
								<?php }?>
							 </select>

							 時
							<select name="seminarStartMinuts[]" id="seminarStartMinuts5">
									<option value="00">00</option>
									<option value="10">10</option>
									<option value="20">20</option>
									<option value="30">30</option>
									<option value="40">40</option>
									<option value="50">50</option>
							 </select>
							 分</p>

					</div>
					<div class="setRestTimebox float-left" style="width: 40%; font-size:14px;">
						<p class="startColor">一般&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; :
							<select name="endHour[]" id="endHour5">
								<?php for($i=1; $i<=24; $i++){?>
								<option value="<?=$i?>"><?=$i?></option>
								<?php }?>
							 </select>

							 時
							<select name="endMinuts[]" id="endMinuts5">
									<option value="00">00</option>
									<option value="10">10</option>
									<option value="20">20</option>
									<option value="30">30</option>
									<option value="40">40</option>
									<option value="50">50</option>
							 </select>
							 分</p>
						<p>セミナー :
							<select name="seminarEndHour[]" id="seminarEndHour5">
								<?php for($i=1; $i<=24; $i++){?>
								<option value="<?=$i?>"><?=$i?></option>
								<?php }?>
							 </select>

							 時
							<select name="seminarEndMinuts[]" id="seminarEndMinuts5">
									<option value="00">00</option>
									<option value="10">10</option>
									<option value="20">20</option>
									<option value="30">30</option>
									<option value="40">40</option>
									<option value="50">50</option>
							 </select>
							 分</p>
					<input type="hidden" name="dayofweek[]" value="5">
					</div>

				</div>
				<div class="restbox clearfix">

					<div class="dayOfWeekbox float-left weekboxHeight" style="width: 20%">
						土曜日
					</div>
					<div class="setRestTimebox float-left" style="width: 40%; font-size: 14px;">

						<p class="startColor">一般&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; :
							<select name="startHour[]" id="startHour6">
								<?php for($i=1; $i<=24; $i++){?>
								<option value="<?=$i?>"><?=$i?></option>
								<?php }?>
							 </select>

							 時
							<select name="startMinuts[]" id="startMinuts6">
									<option value="00">00</option>
									<option value="10">10</option>
									<option value="20">20</option>
									<option value="30">30</option>
									<option value="40">40</option>
									<option value="50">50</option>
							 </select>
							 分</p>
						<p>セミナー :
							<select name="seminarStartHour[]" id="seminarStartHour6">
								<?php for($i=1; $i<=24; $i++){?>
								<option value="<?=$i?>"><?=$i?></option>
								<?php }?>
							 </select>

							 時
							<select name="seminarStartMinuts[]" id="seminarStartMinuts6">
									<option value="00">00</option>
									<option value="10">10</option>
									<option value="20">20</option>
									<option value="30">30</option>
									<option value="40">40</option>
									<option value="50">50</option>
							 </select>
							 分</p>

					</div>
					<div class="setRestTimebox float-left" style="width: 40%; font-size:14px;">
						<p class="startColor">一般&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; :
							<select name="endHour[]" id="endHour6">
								<?php for($i=1; $i<=24; $i++){?>
								<option value="<?=$i?>"><?=$i?></option>
								<?php }?>
							 </select>

							 時
							<select name="endMinuts[]" id="endMinuts6">
									<option value="00">00</option>
									<option value="10">10</option>
									<option value="20">20</option>
									<option value="40">30</option>
									<option value="40">40</option>
									<option value="50">50</option>
							 </select>
							 分</p>
						<p>セミナー :
							<select name="seminarEndHour[]" id="seminarEndHour6">
								<?php for($i=1; $i<=24; $i++){?>
								<option value="<?=$i?>"><?=$i?></option>
								<?php }?>
							 </select>

							 時
							<select name="seminarEndMinuts[]" id="seminarEndMinuts6">
									<option value="00">00</option>
									<option value="10">10</option>
									<option value="20">20</option>
									<option value="40">30</option>
									<option value="40">40</option>
									<option value="50">50</option>
							 </select>
							 分</p>
					<input type="hidden" name="dayofweek[]" value="6">
					</div>

				</div>
				<div class="restbox" style="border: hidden; text-align: center;">
					<input type="submit" name="execute" value="休憩時間を保存">
				</div>
	</form>
			</div>
			<footer class="box footer">
				<p>Copyright © 2010-<?=date("Y")?> FusionOne Co.,Ltd. All Rights Reserved.</p>
			</footer>

		</div>

	</body>
</html>