<!DOCTYPE html>
<html lang="ja">
	<?php require_once '../html/header.phtml';?>
		<script>

		$(function(){
			$('#setRestTime').click(function() {
				if (!confirm('設定した休憩時間で登録します。\nよろしいですか？')) {
					return false;
				}
			});
		});

		</script>
		<title>休憩時間設定画面</title>
	</head>
	<body>
		<div class="container">

			<?php require_once '../html/menuArea.phtml';?>

			<div class="box main-container">

				<table class="restbox titleBlnak">
					<caption id="title">休憩時間設定</caption>
					<tr>
						<td id="dayofWeekTitle">曜日</td>
						<td class="restTimeTitle">休憩開始時間</td>
						<td class="restTimeTitle">休憩終了時間</td>
					</tr>
				</table>

				<form action="settingRestTime.php" method="POST">

					<?php
					$data = $model->getRestTimeData();
					for($i=0; $i<count($data); $i++){
						list($startHour, $startMinuts) = explode(":", $data[$i]['reststarttime']);
						list($endHour, $endMinuts) = explode(":", $data[$i]['restendtime']);
						if($data[$i]['type'] == 1){
					?>

						<table class="restbox">
							<tr>
								<td rowspan="2" class="weekboxWidth"><?=checkDayOfWeek($data[$i]['dayofweek'])?></td>
								<td class="startColor restTimeboxWidth">
									一般&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; :
									<select name="startHour[]" id="startHour0">
										<?php for($j=1; $j<=24; $j++){?>
										<option value="<?=$j?>" <?php if($j == $startHour){echo ' selected';}?>>
											<?=$j?>
										</option>
										<?php }?>
									</select>
									時
									<select name="startMinuts[]" id="startMinuts0">
										<?php for($k=0; $k<6; $k++){ $minuts = $k.'0'?>
										<option value="<?=$minuts?>" <?php if($minuts == $startMinuts){echo ' selected';}?>>
											<?=$k.'0'?>
										</option>
										<?php }?>
									</select>
									分
								</td>

								<td class="startColor restTimeboxWidth">
									一般&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; :
									<select name="endHour[]" id="endHour0">
										<?php for($j=1; $j<=24; $j++){?>
										<option value="<?=$j?>" <?php if($j == $endHour){echo ' selected';}?>>
											<?=$j?>
										</option>
										<?php }?>
									</select>
									時
									<select name="endMinuts[]" id="endMinuts0">
										<?php for($k=0; $k<6; $k++){ $minuts = $k.'0'?>
										<option value="<?=$minuts?>" <?php if($minuts == $endMinuts){echo ' selected';}?>>
											<?=$k.'0'?>
										</option>
										<?php }?>
									</select>
									分
								</td>
							</tr>

					<?php }else{?>

							<tr>
								<td class="restTimeboxWidth">
									セミナー&nbsp;&nbsp;:
									<select name="seminarStartHour[]">
										<?php for($j=1; $j<=24; $j++){?>
										<option value="<?=$j?>" <?php if($j == $startHour){echo ' selected';}?>>
											<?=$j?>
										</option>
										<?php }?>
									</select>
									時
									<select name="seminarStartMinuts[]">
										<?php for($k=0; $k<6; $k++){ $minuts = $k.'0'?>
										<option value="<?=$minuts?>" <?php if($minuts == $startMinuts){echo ' selected';}?>>
											<?=$minuts?>
										</option>
										<?php }?>
									</select>
									分
								</td>

								<td class="restTimeboxWidth">
									セミナー&nbsp;&nbsp;:
									<select name="seminarEndHour[]">
										<?php for($j=1; $j<=24; $j++){?>
										<option value="<?=$j?>" <?php if($j == $endHour){echo ' selected';}?>>
											<?=$j?>
										</option>
										<?php }?>
									</select>
									時
									<select name="seminarEndMinuts[]">
										<?php for($k=0; $k<6; $k++){ $minuts = $k.'0'?>
										<option value="<?=$minuts?>" <?php if($minuts == $endMinuts){echo ' selected';}?>>
											<?=$minuts?>
										</option>
										<?php }?>
									</select>
									分
								</td>
							</tr>
						</table>
						<input type="hidden" name="dayofweek[]" value="<?=$data[$i]['dayofweek']?>">

					<?php }
					}?>

					<div class="restbox" style="border: hidden; text-align: center;">
						<input type="submit" name="execute" value="休憩時間を保存" id="setRestTime">
					</div>

				</form>
			</div>

			<?php require_once '../html/footer.phtml';?>

		</div>
	</body>
</html>