<head>
		<meta charset="UTF-8">
		<link rel="stylesheet" href="../css/design.css">
		<link rel="stylesheet" href="../css/content.css">
		<link rel="stylesheet" href="../jquery/jquery-ui.css">
		<link rel="stylesheet" href="../jquery/spectrum.css">
		<script src="../jquery/jquery-1.11.3.min.js"></script>
		<script src="../jquery/jquery-ui.js"></script>
		<script src="../jquery/spectrum.js"></script>
		<script src="../script/logout.js"></script>

		<?php
		//ログイン画面
		if($_SERVER['PHP_SELF'] == "/attendanceSystem_html/login/login.php"){
		?>

			<script src="../script/loginForm.js"></script>

		<?php
		}
		?>

		<?php
		//メインメニュー機能
		if($_SERVER['PHP_SELF'] == "/attendanceSystem_html/mainMenu/mainMenu.php"){
		?>
			<script src="../script/tabMenu.js"></script>
			<script src="../script/accordion.js"></script>
			<script src="../jquery/datepicker-ja.js"></script>
			<?php if($_SESSION["userinfo"]["authority"] == 2){?>
				<script src="../script/mainMenu-dialog.js"></script>
			<?php }?>
			<script src="../script/mainMenuDisp.js"></script>
		<?php
		}
		?>

		<?php
		//ユーザー登録画面
		if($_SERVER['PHP_SELF'] == "/attendanceSystem_html/insertUser/insertUser.php"){
		?>

			<script src="../script/insertUser.js"></script>

		<?php
		}
		?>

		<?php
		//ユーザー情報変更画面
		var_dump(basename($_SERVER['PHP_SELF']));
		if($_SERVER['PHP_SELF'] == "/attendanceSystem_html/updateUser/updateUser.php"){
		?>

			<script src="../script/updateUser.js"></script>

		<?php
		}
		?>

		<?php
		//勤務時間表（全体）画面&（個人）画面
		if($_SERVER['PHP_SELF'] == "/attendanceSystem_html/overallWorkTime/overallWorkTime.php"
		   || $_SERVER['PHP_SELF'] == "/attendanceSystem_html/personalWorkTime/personalWorkTime.php"){
		?>

			<script src="../script/workTime.js"></script>
			<script src="../script/overallWorkTime.js"></script>

		<?php
		}
		?>

		<?php
		//休日設定画面
		if($_SERVER['PHP_SELF'] == "/attendanceSystem_html/settingHoliday/settingHoliday.php"){
		?>

			<script src="../script/settingHoliday.js"></script>

		<?php
		}
		?>

		<?php
		//休憩時間設定画面
		if($_SERVER['PHP_SELF'] == "/attendanceSystem_html/settingRestTime/settingRestTime.php"){
		?>



		<?php
		}
		?>

		<?php
		//セミナー一覧画面
		if($_SERVER['PHP_SELF'] == "/attendanceSystem_html/eventList/eventList.php"){
		?>

			<script src="../script/eventList.js"></script>

		<?php
		}
		?>

		<?php
		//セミナー登録画面
		if($_SERVER['PHP_SELF'] == "/attendanceSystem_html/insertEvent/insertEvent.php"){
		?>

			<script src="../script/insertEvent.js"></script>

		<?php
		}
		?>

		<?php
		//管理設定画面
		if($_SERVER['PHP_SELF'] == "/attendanceSystem_html/managementElements/managementElements.php"){
		?>

			<script src="../script/managementElements.js"></script>

		<?php
		}
		?>
