<?php

?>
<!DOCTYPE html>
<html lang="ja">
	<head>
		<meta charset="UTF-8">
		<link rel="stylesheet" href="../css/design.css">
		<link rel="stylesheet" href="../css/content.css">
		<script src="../jquery/jquery-1.11.3.min.js"></script>
		<script>

		$(function(){
			$('a[href="login.html"]').click(function() {
				if (!confirm('ログアウトします。\nよろしいですか？')) {
					return false;
				}
			});
		});

		</script>
		<title>エラー画面</title>
	</head>
	<body>
		<div class="container">
			<header class="box">
				<h1 class="title">勤怠管理システム</h1>
			</header>

			<div class="box width70 clearfix">
				<div class="userInfo float-left">
					<p>

					</p>
				</div>
				<div class="userInfo float-right">
					<p><a href="../login/login.php?execute=logout" id="logoutLink">ログアウト</a></p>
				</div>
			</div>

			<div class="box menu"><!-- ヘッダーメニュー-->
				<ul id="dropmenu">
	 				<li><a href="../mainMenu/mainMenu.php">メニュー</a>
	   			 		<ul>
	    				</ul>
	 				 </li>
	  				<li><a href="../overallWorkTime/overallWorkTime.php">勤務時間表</a>
	   					<ul>
	   					</ul>
	 				</li>
	 				<li><a href="../settingHoliday/settingHoliday.php">休日設定</a>
	    				<ul>
	   					</ul>
	 				</li>
	  				<li><a href="#">ユーザー設定</a>
	   					<ul>
	     					<li><a href="../updateUser/updateUser.php">ユーザー設定変更</a></li>

	     					<li><a href="./insertUser/insertUser.html">ユーザー登録</a></li>
	   					</ul>
	  				</li>
	  				<li><a href="../settingRestTime/settingRestTime.php">休憩時間設定</a>
	   					<ul>
	   					</ul>
	  				</li>
				</ul>
			</div>

			<div class="box main-container">
				<div id="errorTitle">
					■ エラー
				</div>
				<div id="errorMsg">
					<?php echo $model->getError();?><br>
					<br>
					<br>

					<div align="center">

						<a href="<?php echo $model->getLp();?>"><?php echo $model->getTitle();?></a>

					</div>
				</div>
			</div>

			<footer class="box footer">
				<p>Copyright © 2010-2015 FusionOne Co.,Ltd. All Rights Reserved.</p>
			</footer>

		</div>
	</body>
</html>
