<!DOCTYPE html>
<html lang="ja">
	<?php require_once '../html/header.phtml';?>
		<title>ユーザー登録画面</title>
	</head>
	<body>
		<div class="container">

			<?php require_once '../html/menuArea.phtml';?>

			<?php if($model->getExecute() == "insert"){?>

				<div class="box main-container">

					<div class="insertUser">

						<p>以下の情報でユーザーを登録しました</p>

							<table align="center" id="padding">

								<tr>
									<td>ID</td>
									<td><?php echo $model->getUserid();?></td>
								</tr>
								<tr>
									<td>パスワード</td>
									<td><?php echo $model->getPassword();?></td>
								<tr>
								<tr>
									<td>名前</td>
									<td><?php echo $model->getName();?></td>
								<tr>
								<tr>
									<td>権限</td>
									<td>
										<?php if($model->getAuthority() == 2){?>
											管理者
										<?php }else{?>
											一般ユーザー
										<?php }?>
									</td>
								<tr>
									<tr>
									<td>勤務形態</td>
									<td>
										<?php if($model->getWorktype() == 1){?>
											常勤
										<?php }else{?>
											非常勤
										<?php }?>
									</td>
								<tr>
								<tr>
									<td>表示色</td>
									<td>
										<font color="<?php echo $model->getColorInfo("code");?>">
											<?php echo $model->getColorInfo("c-name");?>
										</font>
									</td>
								</tr>
							</table>
							<p>
							<a href="">ユーザー登録画面に戻る</a>
							 /
							<a href="../mainMenu/mainMenu.php">メインメニューに戻る</a>
							</p>
						</form>

					</div>

				</div>

			<?php }else{?>

				<div class="box main-container">
					<div class="insertUser">
					<p>ユーザー登録</p>

					<form action="" method="POST">

						<table align="center" id="padding">

							<tr>
								<td>ID</td>
								<td><input type="text" name="userid"></td>
							</tr>
							<tr>
								<td>パスワード</td>
								<td><input type="password" name="password"></td>
							<tr>
							<tr>
								<td>確認用パスワード</td>
								<td><input type="password" name="checkPass"></td>
							<tr>
							<tr>
								<td>名前</td>
								<td><input type="text" name="name"></td>
							<tr>
							<tr>
								<td>権限</td>
								<td>
									<select name="authority">
										<option value="2">管理者</option>
										<option value="1" selected>一般ユーザー</option>
									</select>
								</td>
							<tr>
							<tr>
								<td>常勤/非常勤</td>
								<td>
									<select name="worktype">
										<option value="1" selected>常勤</option>
										<option value="2">非常勤</option>
									</select>
								</td>
							<tr>
							<tr>
								<td>表示色</td>
								<td>
									<?php
										foreach($model->getColorList() as $dex =>$col):
										$count = $dex + 1;
									?>
										<input type="radio" name="colorid" value="<?php echo $col["colorid"];?>"><font color="<?php echo $col["code"];?>"><?php echo $col["c-name"];?></font>
										<?php if($count%4 == 0):?>
											<br>
										<?php endif;?>

									<?php endforeach;?>
								</td>
							</tr>
						</table>
						<p>
							<input type="submit" id="insert" value="登録">
							<input type="hidden" name="execute" value="insert">
						</p>
					</form>
				</div>
			</div>
			<?php }?>

			<?php require_once '../html/footer.phtml';?>

		</div>
	</body>
</html>
