<!DOCTYPE html>
<html lang="ja">
	<head>
		<meta charset="UTF-8">
		<link rel="stylesheet" href="../css/design.css">
		<link rel="stylesheet" href="../css/content.css">
		<title>ユーザー登録画面</title>
		<script type="text/javascript" src="../jquery/jquery-1.11.3.min.js"></script>
		<script src="../script/logout.js"></script>
		<script src="../script/insertUser.js"></script>

	</head>
	<body>
		<div class="container">
			<header class="box">
				<h1 class="title">勤怠管理システム</h1>
			</header>

			<div class="box width70 clearfix">
				<div class="userInfo float-left">
					<p>
						ユーザー名 : <?php echo $_SESSION['userinfo']['name'];?> /
						権限 : <?php if($_SESSION['userinfo']['authority'] == 2){?>
								管理者
							  <?php }else{?>
							  	一般ユーザー
							  <?php }?>
					</p>
				</div>
				<div class="userInfo float-right">
					<p><a href="../login/login.php?execute=logout" id="logoutLink">ログアウト</a></p>
				</div>
			</div>

			<div class="box menu"><!-- ヘッダーメニュー-->
				<ul id="dropmenu">
	 				<li><a href="../mainMenu/mainMenu.php">メニュー</a>
	   			 		<ul>
	    				</ul>
	 				 </li>
	  				<li><a href="../overallWorkTime/ovarallWorkTime.php">勤務時間表</a>
	   					<ul>
	   					</ul>
	 				</li>
	 				<li><a href="../settingHoliday/settingHoliday.php">休日設定</a>
	    				<ul>
	   					</ul>
	 				</li>
	  				<li><a href="#">ユーザー設定</a>
	   					<ul>
	     					<li><a href="../updateUser/updateUser.php">ユーザー設定変更</a></li>
	     					<li><a href="./insertUser.php">ユーザー登録</a></li>
	   					</ul>
	  				</li>
	  				<li><a href="../settingRestTime/settingRestTime.php">休憩時間設定</a>
	   					<ul>
	   					</ul>
	  				</li>
				</ul>
			</div>

			<div class="box main-container">
				<div class="insertUser">
				<p>ユーザー登録</p>

				<form action="" method="POST">

					<table align="center" id="padding">

						<tr>
							<td>ID</td>
							<td><input type="text" name="userid"></td>
						</tr>
						<tr>
							<td>パスワード</td>
							<td><input type="password" name="password"></td>
						<tr>
						<tr>
							<td>確認用パスワード</td>
							<td><input type="password" name="checkPass"></td>
						<tr>
						<tr>
							<td>名前</td>
							<td><input type="text" name="name"></td>
						<tr>
						<tr>
							<td>電話番号</td>
							<td><input type="text" name="phone"></td>
						<tr>
						<tr>
							<td>Email</td>
							<td><input type="text" name="email"></td>
						</tr>
						<tr>
							<td>権限</td>
							<td><select name="authority">
									<option value="2">管理者</option>
									<option value="1">一般ユーザー</option>
								</select>
							</td>
						<tr>
						<tr>
							<td>役割</td>
							<td><select name="positionid">
									<?php foreach($model->getPositionList() as $key =>$val):?>
										<option value="<?php echo $val["positionid"];?>"><?php echo $val["p-name"];?></option>
									<?php endforeach;?>
								</select>
							</td>
						<tr>
						<tr>
							<td>表示色</td>
							<td>
								<?php
									foreach($model->getColorList() as $dex =>$col):
									$count = $dex + 1;
								?>
									<input type="radio" name="colorid" value="<?php echo $col["colorid"];?>"><font color="<?php echo $col["code"];?>"><?php echo $col["c-name"];?></font>
									<?php if($count%4 == 0):?>
										<br>
									<?php endif;?>

								<?php endforeach;?>
							</td>
						</tr>
					</table>
					<p>
						<input type="submit" id="insert" value="登録">
						<input type="hidden" name="execute" value="insert">
					</p>
				</form>
			</div>

			<footer class="box footer">
				<p>Copyright © 2010-2015 FusionOne Co.,Ltd. All Rights Reserved.</p>
			</footer>

		</div>
	</body>
</html>
